### ISSUE TITLE
Implement and Execute Performance Benchmarking

### ISSUE THREAD

**Issue by b-f-chan** [nci-hcmi-catalog/portal#1002]
Build a script to generate 5000 test models to upload into the test environment in preparation of load testing.

Then execute these basic performance benchmarks that will simulate the system under load.

The target number of users for the benchmark testing will be 100 simultaneous public HCMI Catalog site users with a total of 5000 models entered into the system.

The target behaviours of the load test will follow basic public catalog site usage, which includes:

- Searching
- Filtering
- Exporting
- Sorting
- Loading model and variant details
- Exporting variant details

**Comment by mistryrn** [comment]
Performance Benchmarking is complete, report is available here: https://docs.google.com/document/d/1AIWR3jvT6DVfUUlwarQ617DHlUrhnnk7OOgxHjZEYPg/edit#

A bug was discovered in the Search table as a result of loading 5000 models onto the site, logged here for tracking and future investigation: https://github.com/nci-hcmi-catalog/portal/issues/1020

Other than that, the site performs very well even with 5000 models and 100 concurrent users making 500-5000 requests!
