### ISSUE TITLE
Run Accessibility Compliance Checks

### ISSUE THREAD

**Issue by b-f-chan** [nci-hcmi-catalog/portal#1003]
Run accessibility compliance checks on the catalog pages (CMS not required/not in scope)

Use Ax tool plug-in for Chrome (other browsers not required)

**Comment by mistryrn** [comment]
508 Compliance Report for Maintenance Period April-August 2022: https://docs.google.com/document/d/1Ed8Ajor3IYyzENxi48RsGRrsnYykzeKjIPUzyJo8BDs/edit#heading=h.bi90yr6gydt2
