### ISSUE TITLE
Ensure consistent usage of terminology ex. “DNA Methylation Array” to “DNA Methylation”

### ISSUE THREAD

**Issue by scottcain** [nci-hcmi-catalog/portal#1026]
We may need help from Eva to identify all of the items that need updated to ensure consistency.

**Comment by mistryrn** [comment]
Update from Eva on 02/24/2023:

> "Anand had wanted to update the text within the 'Available Molecular Characterizations' table, to change 'DNA Methylation Array' to 'DNA Methylation'. This change would need to be consistent across the Catalog e.g. exported data in the TSV files and within the search panel 'Available Molecular Characterizations' checkbox list."

**Comment by scottcain** [comment]
Done in release 1.20.1
