### ISSUE TITLE
Google analytics update

### ISSUE THREAD

**Issue by scottcain** [nci-hcmi-catalog/portal#1031]
Google analytics is going to be end of lifed next summer, so it needs to be updated before then.

**Comment by mistryrn** [comment]
This is a straightforward upgrade, but it will require some input from whoever currently owns the Google Analytics property for HCMI.
 
We need someone with the “Editor” role to use the Google Analytics 4 Setup Assistant to create a new GA4 property using our existing Universal Analytics tag.
 
There are instructions from Google available here:
https://support.google.com/analytics/answer/9744165
 
Once that is done, I’ll replace our existing UA tag with the new GA4 tag to complete the upgrade.

**Comment by scottcain** [comment]
Done in release 1.20.1
