### ISSUE TITLE
update urls in portal footer

### ISSUE THREAD

**Issue by scottcain** [nci-hcmi-catalog/portal#1041]
Changes needed (per Eva):

* Human Cancer Models Initiative - https://www.cancer.gov/ccg/research/functional-genomics/hcmi
* Change “[ocg.cancer.gov](http://ocg.cancer.gov/)” to Center for Cancer Genomics - https://www.cancer.gov/ccg/
* HHS Vulnerability Disclosure – no edits needed
* Help -[ https://www.cancer.gov/ccg/research/functional-genomics/hcmi/using-hcmi/searchable-catalog](https://www.cancer.gov/ccg/research/functional-genomics/hcmi/using-hcmi/searchable-catalog)
* Contact Us - [NCICCGenomics@mail.nih.gov](mailto:NCICCGenomics@mail.nih.gov)

**Comment by mistryrn** [comment]
Update 03/22/23:
- Case Report Forms URL to be updated to: https://www.cancer.gov/ccg/research/functional-genomics/hcmi/using-hcmi/case-report-forms

**Comment by scottcain** [comment]
Done in release 1.20.1
