### ISSUE TITLE
Style search

### ISSUE THREAD

**Issue by Fgerthoffert** [nci-hcmi-catalog/portal#11]

**Comment by alex-wilmer** [comment]
basic styling -> https://github.com/nci-hcmi-catalog/portal/commit/2dd8ee01b73220b0e1fc4c06234a7ec6e486eb1f

I didn't want to get pixel perfect in this pass. I started drafting a "style spec" to help the css inconsistencies we commonly run into, and to give more control to clients (designers / admins etc)
