### ISSUE TITLE
UX on slider facet

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#114]
- right now we have 4 numbers (range on the bottom, selected on the top) 
- this is for across all portals
- need to find a less confusing way of expressing the slider value
![Screen Shot 2018-06-08 at 5.07.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454fb6b7191a37df1122c4f5b565ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a29841c95df443e54457a517376be47f2431.png)

**Comment by kcullion** [comment]
@rosibaj I think we can make the following improvements:
- include a scale of values so the user can anticipate where they need to move the slider to get their desired value
- include the units in the lowest and highest values
- start the slider values at 0
- display the user's chosen range values in "speech bubbles" to help emphasize the user's choice
- darken the slider bar 

![screen shot 2018-06-11 at 10 16 14 am](https://user-images.githubusercontent.com/18424138/41237211-ffa30612-6d60-11e8-87fa-245d2a43b53a.png)

**Comment by rosibaj** [comment]
@kcullion How would this look when you have numbers in the thousands?

**Comment by kcullion** [comment]
@rosibaj I have removed the unit scale. I left the "ticks" what do you think?

![hcmi-slider](https://user-images.githubusercontent.com/18424138/41438601-cd4774ae-6ff5-11e8-81ea-db419bdee3d9.jpg)

**Comment by rosibaj** [comment]
@kcullion ticks looks good!

**Comment by rosibaj** [comment]
implementation in arranger https://github.com/overture-stack/arranger/issues/431
