### ISSUE TITLE
Facet counts incorrectly filtering themself

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#116]

**Comment by rosibaj** [comment]
>> go to query variant = EGFR G719X (http://hcmi.netlify.com/?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22variants.genes%22%2C%22value%22%3A%5B%22EGFR%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22variants.name%22%2C%22value%22%3A%22EGFR%20G719X%22%7D%7D%5D%7D).  If you look at the facet aggregation count on gene EGFR is 153
>> Add Gene = EGFR and the facet count on gene on EGFR is reduced to 143.  It should still be 153 as all variants of EGFR should have EGFR as a gene . (A thought: perhaps the 10 filtered out are translocation variants with 2 genes, and the bucketing is only counting the first gene, which is not EGFR) 

![Screen Shot 2018-06-10 at 4.07.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f36b7191a37cf1122c4f5b585ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19e41c95df443e74b54a7163663e0742431.png)
![Screen Shot 2018-06-10 at 4.08.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f36b7191a37cf112234f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19141c95df443e74b54a7173f6aef7f2431.png)

**Comment by cy** [comment]
This is due to using `elasticdump` to copy over the generated index, it must have missed some stuff (not sure what) regenerated the index directly on the vm and the problem is gone.
