### ISSUE TITLE
Model List Fonts

### ISSUE THREAD

**Issue by lepsalex** [nci-hcmi-catalog/portal#150]
Available dates displaying in serif-font. should be sans

**Comment by rosibaj** [comment]
@lepsalex I noticed this was only happening on your computer (its sans on mine).  This could be an ubuntu specific issue

**Comment by lepsalex** [comment]
oh maybe

**Comment by lepsalex** [comment]
Probably using a "system font", we would need to embed it if we want to support Ubuntu (or change it to be the same as the other fonts.
