### ISSUE TITLE
Implement google sheets cloning

### ISSUE THREAD

**Issue by Fgerthoffert** [nci-hcmi-catalog/portal#165]

**Comment by rosibaj** [comment]
Create a template google sheet (copy to your own google account)

**Comment by lepsalex** [comment]
Is this still happening?

**Comment by rosibaj** [comment]
https://docs.google.com/spreadsheets/d/1zQ8C0WeFxYlE_1Y591NqqolXud_g1ubrDLMF8iQvV-0/edit#gid=0
