### ISSUE TITLE
UI for images management (CMS)

### ISSUE THREAD

**Issue by Fgerthoffert** [nci-hcmi-catalog/portal#167]
- [x] Model with no images: https://zpl.io/25qPlAr
- [x] Model with uploaded images: https://zpl.io/VqE7MX6
- [x] Edit image metadata (NEW): https://zpl.io/aRYgJ7v
- [ ] Delete warning modal: https://zpl.io/aMqE3Nm

Added to Data model: https://github.com/nci-hcmi-catalog/portal/pull/181

**Comment by rosibaj** [comment]
- grey out with text "Will be deleted on publish"
- include undo delete on image
