### ISSUE TITLE
TMN state field text field with regex validation

### ISSUE THREAD

**Issue by Fgerthoffert** [nci-hcmi-catalog/portal#186]

**Comment by rosibaj** [comment]
SPECS: https://wiki.oicr.on.ca/display/HCMI/Single+Model+Upload

> This field should follow a regular expression of the format T[0-2]M[0-2]N[0-4]
Other text should not be accepted

**Comment by rosibaj** [comment]
Field error for validation: `Field must follow TNM classification format: T0-T2, N0-N4, and M0-M2 ex. T0N1M2`

**Comment by rosibaj** [comment]
tested - looks good!
