### ISSUE TITLE
Implement publish/delete bulk

### ISSUE THREAD

**Issue by Fgerthoffert** [nci-hcmi-catalog/portal#191]
dependency with #194

**Comment by kcullion** [comment]
See mockups:
1. Bulk option dropdown: https://zpl.io/2GQByo3
2. Confirmation for bulk delete: https://zpl.io/aMqExJJ
3. Confirmation for bulk publish: https://zpl.io/aX4GQ6X
4. Error/success messages for bulk publish: https://zpl.io/bevzkqY
5. System error interruption: https://zpl.io/VknKeqG
