### ISSUE TITLE
Add tooltips to table columns

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#198]
For the column headers in the main table, is it possible that the full header names pop-up when browsing over those terms? This will be particularly useful when the screen size of the viewer is not big enough to show the complete table that auto-expands in response to window size.

**Comment by kcullion** [comment]
wondering if this still needs to be done, as the new UI has the table column headers wrapping on two lines if needed:
<img width="1353" alt="2020-06-15_1641" src="https://user-images.githubusercontent.com/18424138/84703979-15a5e380-af27-11ea-8dd7-fe7d75d73345.png">

**Comment by rosibaj** [comment]
In discussion in Phase 2, this is no longer needed due to the redesigned table elements. 

If we need to revisit any tooltips (called scientific explainers) that will be done in a future phase.
