### ISSUE TITLE
Model Type does not show in form page after bulk upload

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#227]
- upload a model (ROSI was uploaded via bulk upload in screenshot) 
- click Edit on the uploaded model
- on the model form page, the Model-Type will be blank, even though it was uploaded with data
- the data showds correctly on the model management page
![Screen Shot 2018-08-24 at 2.48.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f76b7191a37af116234f5e565ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ee04e53a11a3264e0762431.png)
![Screen Shot 2018-08-24 at 2.48.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f76b7191a37af116234f5f565ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19041c95df54ee04e53a11a3264e0772431.png)

**Comment by lepsalex** [comment]
This has to do with the spreadsheet column headers changing from:

Name => Model Name
Type => Model Type

I thought we had said we were dropping the redundant "Model" in the header column and have updated the master spreadsheet to reflect that, this should fix this issue.
