### ISSUE TITLE
Cannot upload a second image

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#275]
On Chrome/Windows 10 

Steps to reproduce:
1. Upload a first image
2.  Drag-n-drop or click to add a second image
3. The browse box pops up and you can select a file, but nothing happens on the ui.  Console errors eventually appear, 
![image](https://user-images.githubusercontent.com/15824252/45700539-d1f82d00-bb3a-11e8-8dd2-07451307666e.png)
![image](https://user-images.githubusercontent.com/15824252/45700703-39ae7800-bb3b-11e8-9c24-cfe6535a4490.png)

**Comment by lepsalex** [comment]
Let's chat about this, I cannot replicate.
