### ISSUE TITLE
Minor Styling Tweaks (MEGA-tix) (public pages) 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#278]
Catalog:
- [x] share dropdown options - make it so they don't appear off the screen (that will fix the horizontal scrollbar that is appearing too)
![screen shot 2018-09-18 at 1 52 59 pm](https://user-images.githubusercontent.com/18424138/45706461-53a38700-bb4a-11e8-90c6-0111ea05305b.png)

- [x] Can you add the bottom white border to the header 
![screen shot 2018-09-18 at 1 58 59 pm](https://user-images.githubusercontent.com/18424138/45706814-391ddd80-bb4b-11e8-8787-805c126e4ca3.png)

- [x] Cart - can you change the font-size of the model name from 16px to 13px so that it fits on one line
![screen shot 2018-09-18 at 2 23 44 pm](https://user-images.githubusercontent.com/18424138/45708060-76d03580-bb4e-11e8-9edb-8ba678837682.png)

- [x] Can you reposition the frequency bars so they are in the middle of the two figures (horizontally and vertically)
![screen shot 2018-09-18 at 3 40 44 pm](https://user-images.githubusercontent.com/18424138/45712056-548fe500-bb59-11e8-831a-aa594e29368a.png)

- [x] Back to search link on the model page: please use the white arrow icon
![screen shot 2018-09-18 at 3 44 12 pm](https://user-images.githubusercontent.com/18424138/45712235-c831f200-bb59-11e8-9f68-a2e78a7afa42.png)
- [ ] For the search text fields, can you implement an "x" icon within the textfield that will clear the user input
![screen shot 2018-09-18 at 2 16 11 pm](https://user-images.githubusercontent.com/18424138/45707659-869b4a00-bb4d-11e8-80dc-a09a603cbb13.png)
- [ ] beagle.css file is overwriting some HCMI styles (like the headlines are taking on Monsterrat instead of LibreFranklin - this has to do with Arranger

**Comment by lepsalex** [comment]
For the search text fields, can you implement an "x" ... opened new ticket here: https://github.com/nci-hcmi-catalog/portal/issues/349

**Comment by lepsalex** [comment]
beagle.css file is overwriting some HCMI styles ... not seeing beagle.css anymore but there are a certainly styles that come in with the arranger components that we need to overwrite, please make a ticket for each of these instances where Monsterrat is still appears.
