### ISSUE TITLE
Add variant table to model entity page

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#28]
Implement the variant table at the bottom of the model entity page: 

https://projects.invisionapp.com/d/main#/console/13747444/286818281/preview
- [x] Three tabs
- [x] if there are less than 11 objects in the table, do not show pagination.  If there are > 10, then show # items and pagination options

Variant tabs:
https://invis.io/KAGGO623WME#/286818281_03-HCMI-Catalog-Entity
https://invis.io/KAGGO623WME#/295697357_03b-HCMI-Catalog-Entity-Variant-Histo
https://invis.io/KAGGO623WME#/295697358_03c-HCMI-Catalog-Entity-Variant-Genomic

This is also in zeplin: https://zpl.io/25yB9NQ

**Comment by rosibaj** [comment]
@cy  looks great so far!  The test data didn't have too many values 😓   Would the tables be paginated by default if they did? 

There are a couple small visual tweaks: 
![image](https://user-images.githubusercontent.com/15824252/40566637-aac15ad2-603f-11e8-836d-2ac36679d227.png)

![image](https://user-images.githubusercontent.com/15824252/40566742-1bc49af0-6040-11e8-9f27-242abef95945.png)

![image](https://user-images.githubusercontent.com/15824252/40566772-467c3c76-6040-11e8-99ee-3350ae67e884.png)

![image](https://user-images.githubusercontent.com/15824252/40566828-8fe03cfa-6040-11e8-97d8-38994fc80058.png)

![image](https://user-images.githubusercontent.com/15824252/40566872-c88c3c52-6040-11e8-9dbb-4ba3d8440001.png)

**Comment by cy** [comment]
@rosibaj yes, if there's more than 10 it will paginate. thanks for the feedback!
