### ISSUE TITLE
Bug: download tsv from cart not working

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#283]
- [ ] When I select some models then open the cart and click the "download tsv" button it doesn't do anything.
- [ ] the file should be named ```HCMI-Model-Catalog-cart.tsv ```
![Screen Shot 2018-09-18 at 3.15.05 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/ab011199-fc60-4046-ab73-2e89e8c2ccd3)

**Comment by rosibaj** [comment]
```HCMI-Model-Catalog-cart.tsv``` sounds like a good name to me?  last updated date doesnt make sense to me in the context of downloading the cart.

**Comment by kcullion** [comment]
@rosibaj sounds good!
