### ISSUE TITLE
Header color issue on Safari

### ISSUE THREAD

**Issue by Fgerthoffert** [nci-hcmi-catalog/portal#296]
The text appears only when one highlights the area (see attached screenshot). Only the middle portion (with the Previous and Next buttons) is visible. The webpages appear as intended on Google Chrome and Firefox. Thought I would share this while we are fixing the organization, location of fields and formatting for this searchable catalog site.
 
![hcmi-sc-screenshot](https://user-images.githubusercontent.com/5667028/45890602-60fe8280-bd91-11e8-85a5-e2c1919e3d55.jpeg)

**Comment by kcullion** [comment]
@rosibaj I think this is a duplicate with: https://github.com/nci-hcmi-catalog/portal/issues/99

**Comment by rosibaj** [comment]
@kim you are right -  i will close as a duplicate
