### ISSUE TITLE
Arranger - Molecular Characterization/Therpy results in page crash

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#323]

**Comment by rosibaj** [comment]
- go to public search
- select values from these fields
- the page will crash

**Comment by rosibaj** [comment]
@lepsalex Myabe we should skip that and just take them out of the table columns if time is a concern?

**Comment by lepsalex** [comment]
Perfect. Thanks!

**Comment by lepsalex** [comment]
Ok, so the custom component is working and the application no longer crashes when selecting a column of "list" type to display in a table. I'm going to close this ticket however we have a new bug where custom types only have data if loaded as a default column in the table, selecting them after the table has loaded results in an undefined value.
