### ISSUE TITLE
Variants no results

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#327]
- [ ] When there are no variants within a model variant tab, please display the message "No variants available" in place of the table (hide the entire table + action bar)
![screen shot 2018-09-18 at 3 23 49 pm](https://user-images.githubusercontent.com/18424138/45711257-fbbf4d00-bb56-11e8-827d-2785ddeccf7c.png)

**Comment by rosibaj** [comment]
@ra-ver @lepsalex  I was assigned to this - can one of you grab it?

**Comment by rosibaj** [comment]
@kcullion Can you attach the Zeplin for this here?

@ra-ver This is working correctly when there are no variants, but can we get a couple ui edits:
- Rounded corners 
- Font color should be the lighter red here
- The side of the box should be wider

**Comment by kcullion** [comment]
Sure - I just did a very basic mockup from a screenshot: https://zpl.io/V0JM6gQ
