### ISSUE TITLE
Arranger - Text input clear with x

### ISSUE THREAD

**Issue by lepsalex** [nci-hcmi-catalog/portal#349]
This is already a ticket in arranger (In all search textfields, add a small 'x' to clear content #823 - https://app.zenhub.com/workspace/o/kids-first/kf-portal-ui/issues/823), needs to be implemented and then brought into HCMI.

Or we can pass in a custom input component I believe and do it that way.

**Comment by rosibaj** [comment]
@lepsalex it would be nicer to have it across all projects in arranger.  this should be a standard feature
