### ISSUE TITLE
2d Chart colors re wrong/not working

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#352]
![Screen Shot 2018-10-10 at 8.56.18 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f36b7191a370f1172d4f5e575edd3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a29941c95df542e04a53a6173565e5712431.png)

**Comment by lepsalex** [comment]
Check again? Works fine locally and on netlify?
![Screenshot from 2018-10-11 10-37-18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5640b3c3ccb7001178e53c/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f27b3dd4b268ee12365258424fa453444d04bea6d37ef5f22e7a98595ae9856c5f27c23815f8bd864ebf01be758e1980e3be825edcfa7f74b9dfd0126754505a9bf54f34a8934acd5bff49e74553a111366ae7647b.png)

**Comment by rosibaj** [comment]
I don'se see the images on left/right? 

<img width="439" alt="screen shot 2018-10-11 at 10 51 49 am" src="https://user-images.githubusercontent.com/15824252/46812914-b6e89980-cd43-11e8-8077-95cc2c7d7423.png">
