### ISSUE TITLE
Add date /updated to admin model edit page title bar

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#360]
Updated date needs to be added to the title bar. 

![Screen Shot 2018-10-10 at 2.51.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f36b7191a37af1172a4f5a5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e04452a11b3160e67f2431.png)

**Comment by rosibaj** [comment]
![Screen Shot 2018-10-17 at 9.31.39 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f46b7191a371f1112a4f5c565edd3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e64556a7143563e1732431.png)

This looks great - Can you add it on all tabs thp (model,image and variant?

**Comment by ra-ver** [comment]
done.
