### ISSUE TITLE
Download template CSV has no data

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#419]
- click the download template 
- @rosibaj has files on her computer that should be downloaded

**Comment by christinayung** [comment]
@rosibaj Should the template be in Excel format?  In CSV, we lose the nice drop downs you've created

**Comment by rosibaj** [comment]
@christinayung Since its downloading a file... that should be possible.  Let me see if the validations are maintained when i export from Google Sheets!
