### ISSUE TITLE
Add tabs to variant table

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#42]
- add tabs to variant table
- three types (structual, biomarkers, sequencing)

**Comment by kcullion** [comment]
Variant tabs:
https://invis.io/KAGGO623WME#/286818281_03-HCMI-Catalog-Entity
https://invis.io/KAGGO623WME#/295697357_03b-HCMI-Catalog-Entity-Variant-Histo
https://invis.io/KAGGO623WME#/295697358_03c-HCMI-Catalog-Entity-Variant-Genomic
