### ISSUE TITLE
Add a "contact us" and link back to the OCG HCMI website

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#430]
We need to add  "contact us" "help" and "ocg.cancer.gov" links to the footer. 
<img width="1107" alt="2020-07-13_1141" src="https://user-images.githubusercontent.com/18424138/87326133-554cf480-c500-11ea-9eb3-be4cfdf89fc1.png">

UI design Zeplin, see footer in this mockup: https://zpl.io/VKRBPLA
All links should open in a new window:
> ocg.cancer.gov can link to https://ocg.cancer.gov/programs/HCMI
> The "Contact Us" link should go to: ocg@mail.nih.gov
> the "Help" link should go to:  https://ocg.cancer.gov/programs/hcmi/frequently-asked-questions

**Comment by akachru-github** [comment]
@kcullion to update mockup reference.

**Comment by rosibaj** [comment]
@mistryrn help link has been confirmed!

**Comment by rosibaj** [comment]
lgtm thanks @mistryrn @joneubank !
