### ISSUE TITLE
Update Variant Migration

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#464]
- [ ] Variant information. Could we add the following PVs: FOXO fusion indeterminate, No FOXO1 rearrangement, TP53 Y234C, TP53 M237I

**Comment by joneubank** [comment]
Documentation RE: migration:
https://github.com/nci-hcmi-catalog/portal#migrations

Example variant migration update file: https://github.com/nci-hcmi-catalog/portal/blob/master/cms/variant-migrations/migrations/20181108152340-insert-variants-181108.js

Need to make a copy/similar version of this for the new variant file to be provided by @rosibaj

**Comment by rosibaj** [comment]
@joneubank sent on slack as cannot attach here

**Comment by rosibaj** [comment]
Deployed and verified with Eva on production (Monday June 24)
