### ISSUE TITLE
Fields not loading in Bulk upload

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#470]
- [x] Therapies is not loading multiple values on upload
- [x] The URL that is being submitted is not being mapped/save to the correct field. 

Example Data to test with:
https://docs.google.com/spreadsheets/d/1FKDpvike6lTFLbbR-OIvxDGxlIYnHUxUEGu93ZXhFHE/edit

**Comment by joneubank** [comment]
Need permission to see your example data doc.

**Comment by rosibaj** [comment]
@joneubank i gave you access! lmk if it didnt worl.

**Comment by joneubank** [comment]
Multiple therapies working well when the values are Pipe Delimited ( `|` character)

**Comment by joneubank** [comment]
URLs are imported if you change the headers in the sheet:
* Change `Model URL` to `Source Model URL`
* Change `Sequence URL` to `Source Sequence URL`
