### ISSUE TITLE
Maintenance- Add/update additional fields

### ISSUE THREAD

**Issue by evatonsingcarter** [nci-hcmi-catalog/portal#472]
- [x] For Esophageal models, under Acquisition site, can 'Esophagus' be added as a permissible value?

- [x] For Model Type, can 'Other' be added as a permissible value?

- [x] For the lung models, the histologic type PVs are a mix of sentence case and title case (e.g. Acinar Adenocarcinoma). Can the PVs be updated to be sentence case?

**Comment by rosibaj** [comment]
@evatonsingcarter Updates sounds good :) I've made a PR so we can get this reviewed and deployed ASAP!

**Comment by rosibaj** [comment]
Change was successfully deployed to production after QA.
