### ISSUE TITLE
Autofocus to search bar

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#475]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/cb3a5688-089d-4d20-b7d7-0ae61ee32136)

**Comment by akachru-github** [comment]
Prioritized higher by the HCMI team at the June 1st bi weekly meeting. Pulling into the sprint.

**Comment by rosibaj** [comment]
Tested on deev site and its working great! 
Also demo'd on June `5th bi weekly meeting
