### ISSUE TITLE
Update header with logo/text

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#48]

**Comment by kcullion** [comment]
The logo has changed and the title on the right is now "HCMI Models Catalog"
![screen shot 2018-05-07 at 10 35 48 am](https://user-images.githubusercontent.com/18424138/39707683-0d6be550-51e3-11e8-818a-01bdf3f5b6f5.png)

**Comment by alex-wilmer** [comment]
https://github.com/nci-hcmi-catalog/portal/pull/49
