### ISSUE TITLE
FE: Adding new fields to the appropriate pages

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#486]
- Add fields to model form in the admin
- Add new fields to model editing form and model page in the catalog

**Comment by touhidulmridha** [comment]
@joneubank - Just re-tested on demo site and found the following issues.

'Model Details' Page: 
- "DAYS TO SPLIT" must be renamed to "TIME TO SPLIT"
- "GROWTH RATE" must be renamed to "DOUBLING TIME"
Link: http://hcmi.cancercollaboratory.org/model/HCM-ROSI-0001-C10?sqon=%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22setId%22%2C%22value%22%3A%22414410d3-7f49-48ee-b68a-0bd82285fb94%22%7D%7D 

CMS - 'Add A Model' page

- "DAYS TO SPLIT" must be renamed to "TIME TO SPLIT"
- "TIME TO SPLIT" must be a free-text entry field.
- "GROWTH RATE" must be renamed to "DOUBLING TIME"
- "DISTRIBUTOR ID" must be renamed to "LINK TO DISTRIBUTOR" 

Another Observation: Hyperlinks under Repository Status > External Resources are missing underline. They should have those underlines as shown in mockup.

Mockups:

Model Details - https://projects.invisionapp.com/share/8YVJSZYC3DZ#/screens/400714280 

CMS - Add a Model - https://projects.invisionapp.com/share/8YVJSZYC3DZ#/screens/400726176

**Comment by joneubank** [comment]
Updates made to the Google Sheet Template: https://docs.google.com/spreadsheets/d/1x5IHiP-75erkvPEoBc0xvBZSpru2ptRiiLMS8ylBZhM/edit#gid=1107755039
