### ISSUE TITLE
Elastic Search mapping / publishing needs to be updated to account for new fields

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#488]

**Comment by joneubank** [comment]
ES index changes must be applied. The commands as would be run in kibana are in the file attached tot his ticket. I will add it to the code base for reference.

**Comment by joneubank** [comment]
[https://app.zenhub.com/files/116159782/8658ce70-ee04-44e9-a897-fba5e66e654b/download](https://app.zenhub.com/files/116159782/8658ce70-ee04-44e9-a897-fba5e66e654b/download)

**Comment by joneubank** [comment]
ES Migration file (kibana commands... will need to convert to curl for CBBIT) 
[https://app.zenhub.com/files/116159782/8b87c457-89c8-4a7a-87b0-6605a52b0fb8/download](https://app.zenhub.com/files/116159782/8b87c457-89c8-4a7a-87b0-6605a52b0fb8/download)
