### ISSUE TITLE
Long load time on model page

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#490]
From Eva's email:

I was poking around on the Searchable Catalog this morning. I filtered on ‘Esophagus’ in ‘Primary site’ and chose one of the models in the viewing pane. When the model specific page opened, there was a long page loading time (~20-30 seconds). This is not typical on the catalog. I have attached a couple screenshots for reference. After this long pause, the page loaded and scrolling through the other filtered model pages appeared normal. I’m not sure if this is an issue on my end or something else. Please let me know if I can provide more information.

Attachments with screenshots. 
![Catalog loading.PNG](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/c642352a-ca7b-4ac3-b81e-342ba881e938)![Inspect-Catalog loading.PNG](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/1cea0fe0-a9f9-4076-8fde-30d8bffcc0b7)

**Comment by akachru-github** [comment]
@rosibaj , @akachru-github  and @joneubank  have been unable to reproduce this issue. We will use this ticket to monitor any further incidents with timestamps to support pulling the logs for investigation.

**Comment by rosibaj** [comment]
Closing this ticket as it has not been observed again in a long time
