### ISSUE TITLE
Data Model: Add "multiple" (related) models relationship

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#506]
- [ ] Document data model updates related to multiple model "sets" here: https://wiki.oicr.on.ca/display/HCMI/HCMI+ES+Model#HCMIESModel-ESDataModel
- [ ] Update MongoDB to include the new "model set" fields

**Comment by touhidulmridha** [comment]
Looks similar to #508....Closing this issue to avoid duplicate.

**Comment by rosibaj** [comment]
closing
