### ISSUE TITLE
FE: Update CMS Portal  - Allow admin to to add/manage multiple models set

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#509]
UPDATED Zeplin link with expanded/unexpanded field: https://zpl.io/br6AEz7
Zeplin Link: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5e18e8387b1d237bccd2cb6d 
Functional Specs link (Row #7): https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=HCMI&title=Managing+Multiple+Models#ManagingMultipleModels-4.FunctionalSpecifications

**Update CMS UI**
**Scenario 1: Adding a new model**
- [x] Add the new `Model Name` section: 
![image](https://user-images.githubusercontent.com/15824252/73566123-13883000-4431-11ea-8043-0db42e2bff60.png)

- [x] Update validation message for name to include the new validation suffix when the name is typed wrong. The message should say:
> Name should follow the format HCM-[4-letter Center code]-[4 number model code]-[ICD10]-[Alphabet suffix]

**Scenario 2: Adding a "multiple model"**
- [x] Populate the dropdown list as a type-ahead field based on existing model names:
![image](https://user-images.githubusercontent.com/15824252/73566341-a2954800-4431-11ea-9b1d-8d9da2e14aaf.png)
- [x] When a user clicks on a linked model, any models in that set should be displayed: 
![image](https://user-images.githubusercontent.com/15824252/73566387-bccf2600-4431-11ea-8a15-add316d92b1a.png)

**Scenario 3: Unlinking a model**
- [ ] Clicking the x in the link field should return the model to an "unlinked" state 
![image](https://user-images.githubusercontent.com/15824252/73566461-e9833d80-4431-11ea-8ef4-eac16389be6f.png)
![image](https://user-images.githubusercontent.com/15824252/73566592-3f57e580-4432-11ea-97f8-40430344d3c5.png)

**Comment by joneubank** [comment]
Link to updated CMS layout: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5e5fcb8ed4cbc8126d25d913
