### ISSUE TITLE
New Field Additions & Updates 

### ISSUE THREAD

**Issue by touhidulmridha** [nci-hcmi-catalog/portal#513]
Following issues were identified during the testing of 3 new fields.

- [x] Add the text to  Link to Distributor  `Please provide the ATCC ID, e.g. PDM-146` in the CMS. 

- [x] "Please provide urls to GDC or EGA." message should apply only to Model URL and Sequence URL fields.

**Comment by akachru-github** [comment]
- Original SOW: "Link to Distributor", 
-- We changed to "Distributor ID" to avoid putting URL's in there.

**Comment by touhidulmridha** [comment]
@joneubank @akachru-github -  Based on latest discussions/communication we should stick with "Link to Distributor" field name in both Model Details and CMS - Add a Model pages. Details provided in ticket 486: https://app.zenhub.com/workspaces/hcmi-5cb5e589cccdd751e9e85a92/issues/nci-hcmi-catalog/portal/486

**Comment by touhidulmridha** [comment]
Thanks Jon! @joneubank - Following issues identified.

Model Details:
Field name “GROWTH RATE” still appears instead of “DOUBLING TIME”
CMS: Add a Model
Link to Distributor field shows example “PMD-146” instead of “PDM-146"

**Comment by touhidulmridha** [comment]
@joneubank  Just re-tested and looks good with the following exception:

Add a Model Page still shows "PMD-146" inside the blank field for "LINK TO DISTRIBUTOR" instead of "PDM-146" (i.e. incorrect ID format). It should say PDM-146.

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/f96d6b14-4c0c-43fd-a78b-182b55ee429f)

**Comment by rosibaj** [comment]
@joneubank A couple issues found in testing:
- [ ] 404 on last updated
![image](https://user-images.githubusercontent.com/15824252/73081976-968c1200-3e96-11ea-8b54-7353dcc79f08.png)
- [ ] Cannot edit models from the model Admin page - see this error:
![image](https://user-images.githubusercontent.com/15824252/73082056-b8859480-3e96-11ea-8b51-09b449da6ba3.png)
Video of crash: https://drive.google.com/file/d/1GHZz2EuZGRYOoGRupnNwhKkYmrfekJbn/view
Edit model from the three dots on model management page to replicate.

**Comment by joneubank** [comment]
Been looking into the crash error... its being caused by our Popup library... @rosibaj any idea what popups are trying to open? Cause thats the culprit.

**Comment by rosibaj** [comment]
@joneubank there should be a menu there that lists `Delete Model` and `Publish` on a single model

**Comment by joneubank** [comment]
Yeup, can reproduce that 100.

It also happens sometimes without that click but I'm sure the solution is the same.

**Comment by joneubank** [comment]
Found fix to issue, way to make the reactjs-popup not crash. :D

**Comment by touhidulmridha** [comment]
@joneubank  Thanks for the fixWorking as expected now.
