### ISSUE TITLE
Deploy and configure new version of Arranger to OICR-DEV (Collab)

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#516]
[ ] Deploy and configuration documentation. Wiki page. Will use this as a base doc for instructions to CBIIT

**Comment by hlminh2000** [comment]
new environment has been deployed to: http://142.1.177.239/

We need to work out transition plan of existing environment to new services as next step.

**Comment by touhidulmridha** [comment]
Tested. Logged a defect accordingly. 
Only documentation pending for this ticket.
