### ISSUE TITLE
Add "RNA-seq of normal" to Molecular Characterizations field

### ISSUE THREAD

**Issue by touhidulmridha** [nci-hcmi-catalog/portal#518]
- [ ] Add "RNA-seq of normal" option with checkbox at the bottom of the list on 'Molecular Characterizations' field in CMS > Add a Model > Molecular Characterizations (list)
![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/0858ef42-15cc-447c-ac14-692715630739)

Demo Link: http://hcmi.cancercollaboratory.org/admin/model

**Comment by rosibaj** [comment]
discussion in meeting with OCG- this value is NOT required currenly. it will not be provided. 

closing this ticket @touhidulmridha !
