### ISSUE TITLE
Error - Invalid Date - Main Search Page - Demo Site

### ISSUE THREAD

**Issue by touhidulmridha** [nci-hcmi-catalog/portal#519]
HCMI demo site shows "Invalid  Date" at the bottom of Searchable Catalog - main search page. It should show the last updated date.

Link: http://hcmi.cancercollaboratory.org/ 
Issue Screenshot:
![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/c36e8b52-b8ae-4de8-9054-ffddd3d21c67)

**Comment by touhidulmridha** [comment]
@joneubank - Saw this issue today too. 

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/6189f09a-4c9d-45a1-9198-ceb9d1b2dac0)

**Comment by rosibaj** [comment]
This ticket has been fixed:
![image](https://user-images.githubusercontent.com/15824252/73189532-896b5f00-40f2-11ea-82f8-2430dedf6c29.png)
I can see the correct updated date in the development environment.  Closing as this ticket is no longer valid. 

(cc @touhidulmridha)
