### ISSUE TITLE
Process Documentation for deployment and configuration new version of Arranger to OICR-DEV (Collab)

### ISSUE THREAD

**Issue by touhidulmridha** [nci-hcmi-catalog/portal#527]
- [ ] Deploy and configuration documentation (for work done as per ticket #516). Wiki page. Will use this as a base doc for instructions to CBIIT

**Comment by touhidulmridha** [comment]
@hlminh2000 - Here is the link to the documentation page on OICR Wiki: https://app.zenhub.com/workspaces/hcmi-5cb5e589cccdd751e9e85a92/issues/nci-hcmi-catalog/portal/527

**Comment by hlminh2000** [comment]
doc has been added at https://wiki.oicr.on.ca/display/HCMI/Deployment+and+Configuration+-+Arranger+Service+on+OICR-DEV

**Comment by touhidulmridha** [comment]
@hlminh2000 - Reviewed. Documentation content is sufficient for now based on slack communication.
