### ISSUE TITLE
Table filter input causing error under 'Search by Name' box on Main Search page

### ISSUE THREAD

**Issue by touhidulmridha** [nci-hcmi-catalog/portal#528]
When model name searched in ‘filter’ search box on right, errors seen on facet panel under 'Search by Name' on left side. 

- [ ] Expected Result: There should no error when searched by word in filter/search bar above search results table. The search results should filter results accordingly based on word search in this field.

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/4126cf2c-8bc9-4797-9514-5b79dec64452)

**Comment by hlminh2000** [comment]
problem identified and fixed in Arranger version `2.0.9`. HCMI portal has been updated at http://142.1.177.239/ to use this latest version

**Comment by touhidulmridha** [comment]
@hlminh2000 - Thanks. Re-tested and passed. 

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/f104f7a8-e68a-45cb-a8c5-718e83523383)

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/cac5686b-03ce-4069-a206-860ee6a82e4f)
