### ISSUE TITLE
UI: Main Search Page

### ISSUE THREAD

**Issue by touhidulmridha** [nci-hcmi-catalog/portal#531]
Mockup Link: https://zpl.io/agprOJA

- [x] Add facet named "HAS MULTIPLE MODELS" with the 3 options: 1) Any 2) Yes 3) No

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/ce3f4b84-cb25-4aca-bc91-01a2afee7b80)

- [x] Add column named "Has MULTIPLE MODELS" in search results table.
- If the model does not have multiples, the value is No with no link
- If the model has multiples, the value is Yes with the number of models that are in that set in brackets
- Clicking on the Yes (#) hyperlink in this column should navigate user to the corresponding row's 'Model Details' page with the carousel being limited to just the set of multiple models

<img width="176" alt="Screen Shot 2020-02-28 at 1 32 23 PM" src="https://user-images.githubusercontent.com/18424138/75576900-d6628e00-5a2e-11ea-8e65-60069dba01c5.png">

- [x] Add doughnut chart named "HAS MULTIPLE MODELS"  in the same section as other doughnut charts.

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/8d995726-94b8-4951-9d26-d756848e034d)

**Comment by rosibaj** [comment]
@joneubank the lgtm - we have added the other tickets and feedback so closing.
