### ISSUE TITLE
UI: Model Details Page

### ISSUE THREAD

**Issue by touhidulmridha** [nci-hcmi-catalog/portal#532]
Mockup Link: https://zpl.io/adGPwZK

- [x] Add field named "TISSUE TYPE" in 'Model Details' section
![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/d9f69fda-b13a-452a-92b6-d581805ea41c)

- [x] Add field named "MULTIPLE MODELS FROM THIS PATIENT" in 'Model Details' section. 
- Related/Linked multiple models must appear as hyperlinks (clicking on which should direct to corresponding 'Model Details' page).
- "TISSUE TYPE" field information must be shown for each linked model.

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/64d72c2c-817e-4d61-bfdf-f4732abb6282)

- [x] Empty state for multiple models: https://zpl.io/bW0kn5K
![Screen Shot 2020-02-18 at 11 54 01 AM](https://user-images.githubusercontent.com/18424138/74758524-73f6da00-5245-11ea-8f12-f734f5104781.png)

**Comment by rosibaj** [comment]
@joneubank the lgtm - we have added the other tickets and feedback so closing.
