### ISSUE TITLE
Perform ES7 Replacement/upgrade in Collab environment

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#536]
Arranger upgrade instructions: https://wiki.oicr.on.ca/display/HCMI/Deployment+and+Configuration+-+Arranger+Service+on+OICR-DEV

ES7 Upgrade instructions: https://app.zenhub.com/workspace/o/nci-hcmi-catalog/portal/issues/537

**Comment by rosibaj** [comment]
scope of this ticket is to switch into the hcmi.cancercollaboratory.org demo site environment in collab
