### ISSUE TITLE
Partial search does not work in Collab environment, but functions in production

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#538]
> Tested on this environment - only searching by the FULL NAME works now. Partial search is not working:
> ![image](https://user-images.githubusercontent.com/15824252/73970766-b2a69f00-48eb-11ea-8d31-dce966b62b00.png)
> 
> To see how this should work, see the production site:
> ![image](https://user-images.githubusercontent.com/15824252/73970810-ce11aa00-48eb-11ea-85c9-0175d0ae3efb.png)

Last comment by Minh: "The bug is also reproducible in QA at http://hcmi.cancercollaboratory.org/, hence this is an issue unrelated to the Elasticsearch upgrade. I've investigated Arranger and Elasticsearch, and although I can theoretically get the feature to work in HCMI, it may require bypassing arranger and/or a new major feature for Arranger. I would like to discuss options further before pursuing a solution."

What we need to ensure is that none of our deployments introduce a regression into production

EXIT CRITERIA FOR THIS TICKET: 
- Identify a root cause for the discrepancy.

**Comment by akachru-github** [comment]
Request ES prod config from CBIIT.

**Comment by akachru-github** [comment]
[Prod config files (elastisearch.yml and jvm.options)](https://app.zenhub.com/files/116159782/727509da-5609-4602-abba-0fd99d6371c4/download)

**Comment by rosibaj** [comment]
@joneubank we have completd this - anything you need to link here?
