### ISSUE TITLE
Update bulk upload file template 

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#544]
Data Dictionary edits are now part of the application, not configured as code.  As external collaborators, we cannot keep the template file up to date any longer. 

Make an exportable Bulk Upload File template based off the editable dictionary, with values coming from the Mongo application collections.

**Comment by rosibaj** [comment]
This issue duplicates https://github.com/nci-hcmi-catalog/portal/issues/521

**Comment by rosibaj** [comment]
@joneubank question:

![image](https://user-images.githubusercontent.com/15824252/83544474-f0978680-a4cb-11ea-8cd3-63b718e53bc7.png)

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/83584937-8bb54e00-a516-11ea-9ca1-0ed761cf712e.png)
