### ISSUE TITLE
Multiple Models Feedback

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#545]
- [x] Need to update name validation to include a -letter at end 
![image](https://user-images.githubusercontent.com/15824252/77698761-8cb28800-6f87-11ea-8f27-4fbaaf0fbc84.png)
- [x] Make the unexapnded field required for publish
![image](https://user-images.githubusercontent.com/15824252/77698861-b79cdc00-6f87-11ea-99b7-9df2e3db48cd.png)

- [x] Exclude current model from model linkage typeahead search
![image](https://user-images.githubusercontent.com/15824252/77698993-efa41f00-6f87-11ea-88a0-99702a22fa68.png)

- [x] For consistency with table column, change facet title to "Has Multiple Models"
<img width="293" alt="Screen Shot 2020-03-27 at 9 33 00 AM" src="https://user-images.githubusercontent.com/18424138/77761184-055c2780-700e-11ea-86b0-f417d184223e.png">

- [x] change this number to reflect the total number in the set (so in this example it should be 2)
<img width="888" alt="Screen Shot 2020-03-27 at 9 53 15 AM" src="https://user-images.githubusercontent.com/18424138/77763015-cd0a1880-7010-11ea-998d-57035e31eba9.png">

- [x] When tissue type is N/A for the multiple models, but Tissue Type: N/A here too
<img width="249" alt="Screen Shot 2020-03-27 at 10 02 36 AM" src="https://user-images.githubusercontent.com/18424138/77764005-4f470c80-7012-11ea-8598-a62f80b4e088.png">

- [x] When I click on the graph for "Has multiple models" I get an error
<img width="1612" alt="Screen Shot 2020-03-27 at 10 47 34 AM" src="https://user-images.githubusercontent.com/18424138/77768140-70aaf700-7018-11ea-8ebd-eabaa7e86a6a.png">

- [x] Instructions for linking models. I think we should be clear and revise this to be: Start typing model name to look up existing models. You only need to link to one model in the set.

- [x] Capitalize the "Published, Unpublished, Changes not yet published" and link these to their corresponding models (open in a new tab)
<img width="529" alt="Screen Shot 2020-03-27 at 11 22 36 AM" src="https://user-images.githubusercontent.com/18424138/77772092-f8473480-701d-11ea-8a1f-0d70d305b0d4.png">

**Comment by joneubank** [comment]
Deleting a model is something I didn't consider. Will have to update matched models when one is deleted.

**Comment by joneubank** [comment]
`When I unpublished that model, and went back to the catalog - the model still shows up in the list of linked models - but when I click on it goes the a blank page and breaks my back button`

In order to accomplish this, when a model is unpublished we will need to PUBLISH all the model's in it's set. Is that what you want?

A middle ground fix is to mark the other model's in its set as `published with changes`.

**Comment by joneubank** [comment]
> Probably not high priority...but if time, reorder the CMS edit/add model form to reflect the new order and groupings on the model page: https://zpl.io/br6AEz7

Need clarification, don't know what I am re-ordering and where, and what is the order.

**Comment by rosibaj** [comment]
> A middle ground fix is to mark the other model's in its set as `published with changes`.
I think right now this is the path to take.

**Comment by rosibaj** [comment]
> > Probably not high priority...but if time, reorder the CMS edit/add model form to reflect the new order and groupings on the model page: https://zpl.io/br6AEz7
> 
> Need clarification, don't know what I am re-ordering and where, and what is the order.

@joneubank @kcullion This is not priority.  This can be done when we reskin admin with the editable dictionary.  I will remove this point for now.

**Comment by joneubank** [comment]
> From the CMS - if my model is linked to other models, and I change the status to unpublished - it clears the linked models on the form. But when I refresh, those linked models re-appear

You didn't save. Do you want these matches to be saved immediately on selection? If so then I need to disable this section until you have saved the model at least once.

**Comment by kcullion** [comment]
@joneubank if I go to a model that is published (and saved with the matched models), change it to unpublished, the fields associated with the matched model clears. I had already saved that linkage before?

**Comment by joneubank** [comment]
@kcullion i may need you to demo this so i understand, can we look at it monday?

**Comment by joneubank** [comment]
@rosibaj >clicking on the header for "Has multiple models" isn't sorting properly..this happens

looks like an arranger bug with sorting nested fields by total count. might not be but i also cannot sort in the table files count or variants count (similar to matched models count in structure). will need more investigation into a solution, but for now i will disable sorting on that column temporarily.

**Comment by kcullion** [comment]
@joneubank sure I can demo quickly on Monday. I really don't think it's a big issue thinking about it more.

**Comment by joneubank** [comment]
@rosibaj I am going to make a new release now that should cover the items checked. Can you make separate tickets for the remaining issues? they either need discussion or are a significant piece of work on their own.

**Comment by rosibaj** [comment]
@joneubank will do after i review the release!

**Comment by rosibaj** [comment]
@joneubank the lgtm - I have now split remaining items into new tickets so closing.
