### ISSUE TITLE
Search Results: remove initials and change 2nd value

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#546]
With the search results for "search by name" facet, please:

- [ ] Remove the "MO" icon and replace with model icon in: https://zpl.io/Vqq1xG6
- [ ] Change the second value from repeating the name, to the primary site value for that model
<img width="289" alt="Screen Shot 2020-03-27 at 11 06 29 AM" src="https://user-images.githubusercontent.com/18424138/77770046-0778b300-701b-11ea-82e7-170ab2a74a08.png">

In new UI style should look like:
<img width="246" alt="2020-06-15_1637" src="https://user-images.githubusercontent.com/18424138/84703582-800a5400-af26-11ea-81eb-47cf68bfe07b.png">

**Comment by rosibaj** [comment]
this was done with the GVI work 
![image](https://user-images.githubusercontent.com/15824252/90258588-c5f47300-de16-11ea-8dbe-488d48429a6a.png)
