### ISSUE TITLE
BE:  Abstract `constants` file to Mongo DB Collections 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#548]
Currently add codelist values exists as values in this constants file: 
https://github.com/nci-hcmi-catalog/portal/blob/ed38e67dae643244d748959e6c73413dcda4891f/cms/src/schemas/constants.js

In order to move the dictionary terms out of code and into the application, we need to abstract field values from this constants file into an application managed Mongo collection. 

- [x] Create the mongo collections 
- [x] Move the values from the constants file into Mongo DB

**Comment by joneubank** [comment]
https://github.com/nci-hcmi-catalog/portal/pull/579
