### ISSUE TITLE
BE: Refactor CMS Admin pages to connect to Mongo codelist collections

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#549]
The CMS currently reads values for dropdown fields from the constants file.  This needs to adjusted to the new mongo collection.  For example:
![image](https://user-images.githubusercontent.com/15824252/77947609-2df45380-7292-11ea-9ceb-1aa52047a711.png)

- [x] For each required field (2.1 on [this table](https://wiki.oicr.on.ca/display/HCMI/CMS+Editable+Dictionary#CMSEditableDictionary-4.FunctionalSpecifications)) make sure that the form field is connected correctly to the new db

**Comment by rosibaj** [comment]
- [ ]  I cannot populate the `tissue type` field:
![image](https://user-images.githubusercontent.com/15824252/81724657-bd288580-9452-11ea-883f-4682d3ef3daa.png)
- [ ]  I cannot "save" a new model to create it. 
![image](https://user-images.githubusercontent.com/15824252/81724889-185a7800-9453-11ea-848a-04e471cd6968.png)
![image](https://user-images.githubusercontent.com/15824252/81724924-23ada380-9453-11ea-9e03-dd1394776ba6.png)

**Comment by rosibaj** [comment]
- [ ] When i try and publish i get this error: 
![image](https://user-images.githubusercontent.com/15824252/81727926-b05a6080-9457-11ea-93fc-de1d03618d21.png)

But there is no indication on the front end `which` required field i am missing

- [ ] Additionally, it appears that the field validation errors are also now missing: 
![image](https://user-images.githubusercontent.com/15824252/81728105-ebf52a80-9457-11ea-8b31-f72b169df569.png)

**Comment by joneubank** [comment]
Could not reproduce the publish error. I am working on the primary site error message.

**Comment by rosibaj** [comment]
Tested: 
- Was able to add `Tissue Site` correctly now
- Validations are now correctly working.  I was not able to publish without having all required fields filled in; the publish button was correctly disabled until i filled in all required fields. 
- once all required fields were filled in, the button enabled and i was able to publish the  model.
- no observed regressions in matched model behavior in this process

**Comment by rosibaj** [comment]
@joneubank this looks great! thank you!!!!
