### ISSUE TITLE
handle "no results"

### ISSUE THREAD

**Issue by alex-wilmer** [nci-hcmi-catalog/portal#55]

**Comment by alex-wilmer** [comment]
<img width="1436" alt="screen shot 2018-05-07 at 11 44 16 pm" src="https://user-images.githubusercontent.com/2880089/39736926-975541d6-5250-11e8-9f3c-352664eecfbe.png">

**Comment by kcullion** [comment]
Mockup for no results...
![05 hcmi-catalog-noresults](https://user-images.githubusercontent.com/18424138/41168263-7466c182-6b13-11e8-925a-b112cf0ad91c.jpg)

**Comment by rosibaj** [comment]
closing as #282 is duplicate
