### ISSUE TITLE
UI: Connect Add to Fields & create a Dictionary Draft

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#555]
- [x] Add a field UI.  When you click on a value it a field, it becomes an editatable text box. 
https://projects.invisionapp.com/d/main#/console/19284541/402652793/preview
- [x] Once you **click save at the end of the field** or **click away**, the value becomes saved and a new dictionary draft is saved.  Once the draft exists, several UI components change:
https://projects.invisionapp.com/d/main#/console/19284541/402652795/preview
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/9f5ff3d3-9ae1-4621-a198-49c22621e710)
- [x] Until publish, all further changed to the dictionary are saved to this dictionary draft. Only one dictionary draft can exist at a time. 

New Draft action bar -https://zpl.io/ad0dAL5
<img width="1178" alt="Screen Shot 2020-05-04 at 10 46 21 AM" src="https://user-images.githubusercontent.com/18424138/80981073-70600180-8df7-11ea-9310-9f5fef26d4f9.png">

**Confirmation modals:**

- [x] When admin presses "reset" they should get the following confirmation modal:
https://zpl.io/bozmkRX

- [x] When admin presses "publish all updates" they should get the following confirmation modal:
https://zpl.io/am0P15r

**Comment by akachru-github** [comment]
Changes:

Cancel -> Reset
- Reset would go back to the currently published dictionary

Remove "Save" and make it save in realtime as changes are being made. Each change will be sent to the BE as it is entered. Changes will be saved to a draft rather than having an explicit user action required. 

Add "last updated" timestamp next to "Draft" pill.

**Comment by kcullion** [comment]
@mistryrn here's a screenshot of the new draft action bar
<img width="1140" alt="Screen Shot 2020-05-04 at 10 43 09 AM" src="https://user-images.githubusercontent.com/18424138/80978455-11e55400-8df4-11ea-89fb-70d2d3c41a5c.png">

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/82071041-872e1000-96a3-11ea-9af0-afaa8900412c.png)

After investigating the error: 
![image](https://user-images.githubusercontent.com/15824252/82071070-8f864b00-96a3-11ea-899a-67742e225496.png)

2 errors to fix:
- [ ] the UI shouldn't freeze in this case.  We should get an error toast notifying the user of the issue (same error bars as used in other pages)
- [ ] the API response is an issue in this case - i should be able to edit BOTH the clinical tumor diagnosis AND its dependent values in one draft

**Comment by rosibaj** [comment]
Tested 
- was able to change a `clinical tumor diagnosis` and then a `dependent` value
- the draft saved and published successfully with both changes.
