### ISSUE TITLE
UI: Connect Publish Button to service

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#556]
- [x]  Connect the publish button to the new publish service for the dictionary .
The button should be disabled if no draft dictioary, and enabled if there is a draft available. 
- [x] Implement the confirmation button before publish
Zeplin: https://zpl.io/am0P15r

**Comment by mistryrn** [comment]
Included in this PR: https://github.com/nci-hcmi-catalog/portal/pull/590

**Comment by rosibaj** [comment]
@mistryrn one small thing about this modal: 
![image](https://user-images.githubusercontent.com/15824252/82072695-1805eb00-96a6-11ea-8cb6-03fc0bfa4b92.png)

**Comment by rosibaj** [comment]
@mistryrn one additional thing:  the success message state did not get implemented: 
![image](https://user-images.githubusercontent.com/15824252/82348256-988a5b80-99c6-11ea-8412-0234ce202c15.png)

Can you please add the confirm banner if the dictionary successfully published?

**Comment by rosibaj** [comment]
banners looks good, but one issue - the number in the banner is coming through as "undefined"
![image](https://user-images.githubusercontent.com/15824252/82478661-3c473a80-9a9f-11ea-89e4-1c9104cb168e.png)

**Comment by joneubank** [comment]
https://github.com/nci-hcmi-catalog/portal/pull/612

**Comment by rosibaj** [comment]
I have tested the updated
- works correctly with success message and publish when 0 models are updates
- works correctly with confirmation message when a numner (1 or more) models are updated
