### ISSUE TITLE
Carousel goes to 0 on refresh

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#557]
- [ ] Refreshing on a model page cause the carousel to read 0 of 0, even though the url/set is the same 
![image](https://user-images.githubusercontent.com/15824252/78036509-6189b900-7338-11ea-83a2-befebe557eee.png)

- [ ] Add functionality for carouselling through multiple sets. So from the table, when I click on "Yes (3)" it should take me to that model in the set of 3 and I should just see 1 of 3 in that carousel and move through just the set of multiple models. Right now I see the entire carousel:
<img width="516" alt="Screen Shot 2020-03-27 at 10 49 54 AM" src="https://user-images.githubusercontent.com/18424138/77768521-f8910100-7018-11ea-8da3-ec29877e5b5a.png">

- [ ] Also when this is fixed, just make sure this count is correct in the table. It may also be counting the unpublished linked models
<img width="184" alt="Screen Shot 2020-03-27 at 11 49 09 AM" src="https://user-images.githubusercontent.com/18424138/77774186-0d719280-7021-11ea-88aa-75f59e00196f.png">

**Comment by akachru-github** [comment]
Check CBIIT dev environment to confirm whether this was introduced by ES7 upgrade.
