### ISSUE TITLE
Multiple Model Header is not sorting in table

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#558]
- [ ] clicking on the header for "Has multiple models" isn't sorting properly..this happens
<img width="1327" alt="Screen Shot 2020-03-27 at 9 59 01 AM" src="https://user-images.githubusercontent.com/18424138/77763570-abf5f780-7011-11ea-8e1d-ea00e2b001ee.png">

**Comment by akachru-github** [comment]
Sorting is now disabled entirely to fix the strange error state. 
Closing this.
