### ISSUE TITLE
Restyle Patient Details 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#561]
- [ ] Update and re-organize  "Patient Details" section as shown in the screenshot below with corresponding field order.
- Add "TISSUE TYPE" field in 'Patient Details' section.

![image.png](https://images.zenhubusercontent.com/5de15e4e49a5b4866c2db1ba/498de170-d1d5-4b29-841a-a6fc7961fe17)

**Comment by kcullion** [comment]
closing as this will be taken care of on: https://github.com/nci-hcmi-catalog/portal/issues/602
