### ISSUE TITLE
Fix Cart Export to not include weird fieldname references

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#576]
- verified to not be on production 
- only on multiple models deploy

##  Steps to Reporduce 
1. ![image](https://user-images.githubusercontent.com/15824252/80250975-cf2cba80-8642-11ea-9d5b-6b0511e01f0c.png)
2.  Open TSV
![image](https://user-images.githubusercontent.com/15824252/80251003-d94eb900-8642-11ea-8c77-0d343c0a706b.png)

## Expected behaviour 
Should not include `edge` and `object object` but instead fields/fieldnames

**Comment by joneubank** [comment]
Something else modified the data structure that was mapped into the tsv exporter, it was easy enough to remove the unwanted fields now that we know they are there. https://github.com/nci-hcmi-catalog/portal/commit/d72f05a06a84a66d6eb8fb4a6758e0f4efad7dd9
