### ISSUE TITLE
Bulk Upload Overwriting Variants incorrectly 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#582]
Variants are being overwritten in the model bulk upload `overwrite` option. 

## Steps to reproduce
1. Add variants to the `HCM-ZZZZ-0001-A01` model  (https://docs.google.com/spreadsheets/d/11ipKrohRyoNuVGRZ35y2r4agbAz_ZQDm8JEWu-aDFzs/edit#gid=1556546328)
![image](https://user-images.githubusercontent.com/15824252/80982366-3a238180-8df9-11ea-9fa3-55e1534a08ae.png)

2. Edit the bulk model upload for that model and upload the bulk changes. Make sure to select the `Yes, overwrite existing models` option.
https://docs.google.com/spreadsheets/d/1-SlmBBjlRHP_JPIPGlHLG988oN_XpS-KcMT17Vmc1hA/edit#gid=1107755039
![image](https://user-images.githubusercontent.com/15824252/80982804-cb92f380-8df9-11ea-9f3a-d91d69219d6a.png)

3. Look at the newly bulk uploaded model in the variant section. All variants have been erased. 
![image](https://user-images.githubusercontent.com/15824252/80982337-3132b000-8df9-11ea-8f0f-ebcf081bc3a8.png)

## Expected Behavior 
- Selecting the `overwrite` option on bulk model upload should only edit model details 
- Selecting the `overwrite` option on bulk variant upload should only affect variant data (working as expected)

**Comment by joneubank** [comment]
https://github.com/nci-hcmi-catalog/portal/pull/583

**Comment by rosibaj** [comment]
closing as has been deployed to prod already
