### ISSUE TITLE
Entity page Image Carousel

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#60]
- ~~Ability to view image larger~~ (duplicate below)
- [x] If a model has more than one image, it should be a carousel with < > arrows 

Pick whatever library/plugin you think is best and we can brand it after.  

Example: 
<img width="1034" alt="screen shot 2018-05-11 at 1 29 49 pm" src="https://user-images.githubusercontent.com/15824252/39937983-68410156-551f-11e8-938a-01aefb82d875.png">

**Comment by kcullion** [comment]
@lepsalex the gallery looks good. I think two nice-to-have things would be:

- [ ] Add some padding around the arrows but increase the hit target area around the arrow so it's easier to click on it.
![screen shot 2018-09-18 at 4 42 17 pm](https://user-images.githubusercontent.com/18424138/45715326-04695080-bb62-11e8-9246-75fdb5a503f9.png)

- [ ] Allow for user to make the image gallery larger, and navigate through larger versions of the images.

**Comment by rosibaj** [comment]
Example with multiple images: 
https://hcmi.netlify.com/model/HCM-BROD-9989.C79
