### ISSUE TITLE
UI: Restyle Catalog Search Page

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#601]
Update the catalog style:
**Zeplin:** 
not searched: https://zpl.io/b6dozKg
search query applied: https://zpl.io/ag4BY30

**Summary of changes:**
- [x] 1. New header - Kim will send a new banner image. The header has gotten shorter, brighter and the text is now white
- [x] 2. Facet panel - updated styles - tighten up, primary items are bolder and not capitalized. Follow zeplin styles
- [x] 3. Overall page - background is now white and padding around content cards has gotten smaller - the aim of this new design is to tighten things up so that more appears on the page without scrolling. Make sure body font default colour is black, not dark grey.
- [x] 4. Query box - background is grey now. Updated tag and button styles too, as well as colour of model list icon. See both searched, and searched mocks above. 
- [x] 5. Chart card - it's now not as tall. New colours - Kim will specify shortly
- [x] 6. Table header - doesn't have a 'card' around it - text is smaller. tighten up and make it appear closer to the table. New button style. Do not implement the toggle for now
- [x] 7. Table body - font is 12px, tighten up the row height as per the mock. Headers are now not capitalized, but bolded with a white background. Can we make the header labels wrap on to two lines? If not, leave as it. 
Zebra stripe colour has been darkened slightly. Use same checkmark styling as facet panel (if too hard to change from the default blue, then just leave that). Expansion status column - with colour coded "Expanded" (#3f8342) - green and "Unexpanded" - orange (#be541a)
- [x] 8. Table footer - pagenation style has changed slightly. Move the "updated" date inside this footer to tighten up the space.
- [x] 9. Page footer - tightened up. Space out logos to fill the space more.
<img width="1102" alt="hcmi-catalog-ui-updates" src="https://user-images.githubusercontent.com/18424138/82350220-0f285880-99c9-11ea-8201-198dc39225e1.png">

**Comment by akachru-github** [comment]
This ticket does not include the Unexpanded toggle.

**Comment by kcullion** [comment]
it's looking great @mistryrn !
Can you please:
- [ ] Make sure the table footer follows the last row of the table. So no blank white space if there are less than 20 models
<img width="1359" alt="2020-06-01_1628" src="https://user-images.githubusercontent.com/18424138/83451452-f9814d00-a424-11ea-84db-4d70d345cb3c.png">
- [ ] Make the No and Yes values line up (I think the yes is using some button padding styles)
<img width="167" alt="2020-06-01_1633" src="https://user-images.githubusercontent.com/18424138/83451897-b4114f80-a425-11ea-82e8-88e3da65592e.png">

**Comment by mistryrn** [comment]
> * [ ]  I noticed this happens on the production site too, if a facet is closed and the user clicks the search icon I think it should open the facet search box and values. Right now it does nothing. @rosibaj is this out of scope for this ticket?
> 
> <img alt="2020-06-01_1641" width="297" src="https://user-images.githubusercontent.com/18424138/83452480-c770ea80-a426-11ea-80d4-e0e9a0fd79a7.png">

@joneubank would a fix for this need to be applied in Arranger? I can't think of a way to do it within the hcmi code myself

**Comment by rosibaj** [comment]
@mistryrn noticed these issues: 

- [ ] more responsive resize
![image](https://user-images.githubusercontent.com/15824252/83543824-035d8b80-a4cb-11ea-93cd-d8b16bcdad8e.png)

**Comment by kcullion** [comment]
@mistryrn can you also change the row hover colour for the table to this:#F2F2F8 so it's slightly different than the zebra stripe.

**Comment by kcullion** [comment]
@rosibaj this hasn't really been made responsive... (charts will go outside the box) do you want us to discuss how the catalog page/model page should look on tablet?

**Comment by mistryrn** [comment]
> @mistryrn can you also change the row hover colour for the table to this:#F2F2F8 so it's slightly different than the zebra stripe.

Sure thing – should I do that for just the row hover, or change the hover for all interactive elements to be #F2F2F8 as well?

**Comment by kcullion** [comment]
good question @mistryrn - can you try just making the zebra stripe #F2F2F8 and leaving the hover as is. We'll see how that looks

**Comment by kcullion** [comment]
looks great, thanks @mistryrn !

**Comment by rosibaj** [comment]
acquisition site moved to https://github.com/nci-hcmi-catalog/portal/issues/632
