### ISSUE TITLE
UI: Restyle Model Details Page

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#602]
Two mockups show different variations of this page:

**Expanded model - with multiple models, images and variants: Zeplin: https://zpl.io/be0PpgW**
- [x] 1. Model title bar: revise style of title (add colon after the word model), move the share and add to my list buttons inside the title bar. Add the expanded/unexpanded tag. revise top and bottom pagenation to say "next and previous" instead of the specific model ids.  Change styling of all buttons to reflect mockup. 
- [x] 2. implement new card design with new yellow title and tightened table content inside. Overall body content has been made black and smaller (font-size:13px;)
- [x] 3. Split out the multiple models into it's own card and add the count to the title. Font size has been made smaller here, and a divider line between models.
- [x] 4. Available molecular characterizations has been split out and changed into a chart format. Note: RNA-seq of normal is not an option here so that box will always contain an "x" (or should it be N/A @rosibaj ?)
- [x] 5. Patient details. Add bullet points for "therapy" items. Add "Tissue type" field in this section.
- [x] 6. Model images: add image count to title. Make images slightly smaller if need-be to fit in this new grid. (the mockup arrows show the disabled state, i.e. when the model has only one image)
- [x] 7. Repository status: just adopts new card style
- [x] 8. External resources: instead of a table, these become buttons using the new button styles. If that field is blank for a model, the button is disabled. For the link to distributor button, change label to "Visit PDM-### to Purchase".
- [x] 9. Variants card: uses new table and button styles from catalog page. Also uses new simplified tab style from dictionary UI. 
<img width="1096" alt="hcmi-model-expanded" src="https://user-images.githubusercontent.com/18424138/82364308-1ce7d900-99dd-11ea-9194-82c68b266a1d.png">

**Unexpanded model - multiple models, images and variants are empty:** Zeplin: https://zpl.io/2EJ9N7g

- [x] 1. Model titlebar: for unexpanded models, the tag becomes orange
- [x] 2. Empty multiple models: when a model has no multiples, card shows a message and title count is zero.
- [x] 3. Empty images card: when a model has no images, card shows a message and title count is zero.
- [x] 4. External resources: Hide the "Visit PDM-### to Purchase" button for unexpanded models.
- [x] 5. Empty variants: showing the empty state when no variants exist
<img width="1104" alt="hcmi-model-unexpanded" src="https://user-images.githubusercontent.com/18424138/82366135-bca66680-99df-11ea-9e8a-be38e121f3ca.png">

**Comment by mistryrn** [comment]
A bug related to the "Back to search" button has been identified and fixed along with the UI work on this ticket. If a user was to hard refresh on a Model Details page and then click the "Back to search" button, it would send empty `sqon` to Arranger, causing the facets panel to crash.

We are now checking for empty `sqon` before routing back to the results page, which will prevent this from happening.
