### ISSUE TITLE
Update Arranger to not create junk indices in ES

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#605]
- Arranger is getting hit by CBIIT internal security check
- Arranger is hitting ES with junk indices based on the check
- Create a script to reproduce the issue in the OICR environment. 
- Update Arranger to block the creation of junk indices

**Comment by rosibaj** [comment]
This issue is resolved with an Arranger version update:

https://github.com/overture-stack/arranger/pull/585
