### ISSUE TITLE
Dashes break the autocomplete search.

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#606]
The autocomplete search is breaking when dashes are used. 

#Steps to Reproduce
1. Type "hcm" in the search - you will see it correctly return models.
1. Type "hcm-" in the search. No models are returned. this is incorrect. this should match all models. 

Video of the issue:
https://drive.google.com/file/d/1xbnXkN569k8Sg66S0W1ZEqRL5whg2n2A/view

## Technical description of issue
In order to do free text search in a user-friendly manner, elasticsearch uses something called ["analyzers"](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-tokenizers.html) that interpert text in different ways to account for how users may type.  For example, a common analyzer is `lowercase` which allows for cases-insensitive string searching.  

In the current index, it appears that due to an update the current set of analyzers have a set of conflicting rules. 

- ability to do partial match, match from start or middle
- must be case insensitive 

The problem is the tokenizer splitting the word at the hyphen, interperting each part of the HCMI identifier as a "separate" word. 

# Potentail Solutions
- Update the mapping analyzers including:  update the tokenizer from `standard` (the default for this is a dash) to `whitespace`
- republish the index with the new autocomplete fields populated according to the new index

**Comment by akachru-github** [comment]
Confirmamtion: 
- Can we republish current content? If so, we can write a scrip that handles this that Cuong would run.

**Comment by joneubank** [comment]
PR: https://github.com/nci-hcmi-catalog/portal/pull/671
