### ISSUE TITLE
UI: Restyle Add to list panel

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#608]
When a user selects a model, it adds it to their list for download.

- [ ] New buttons styles for selected model and list icon. Zeplin: https://zpl.io/advwOAn
<img width="188" alt="Screen Shot 2020-05-19 at 2 50 54 PM" src="https://user-images.githubusercontent.com/18424138/82366453-34749100-99e0-11ea-80b7-edba935fe4b0.png">

When user clicks on the list icon, it opens a "drawer". Please update these styles.
Zeplin: https://zpl.io/Vqj5qrJ

- [x] 1. Drawer titlebar: new background and title styles. New number icon and button styles
- [x] 2. Model teaser: new garbage can icon and change font styles (bold, black instead of red).
- [x] 3. Download tsv button: use new dark teal button style. Same background as the titlebar
<img width="264" alt="hcmi-model-drawer" src="https://user-images.githubusercontent.com/18424138/82366827-dac09680-99e0-11ea-84b3-cbcde6e67b62.png">

Empty list state: Zeplin: https://zpl.io/aXA1qZp
- [x] Implement new styles for empty state
<img width="250" alt="Screen Shot 2020-05-19 at 3 03 17 PM" src="https://user-images.githubusercontent.com/18424138/82367504-e6608d00-99e1-11ea-80b7-31af764fc250.png">

**Comment by kcullion** [comment]
@mistryrn this looks good! The first item I'm sure you will do with the model page :)

**Comment by rosibaj** [comment]
lgtm - all the buttons are working :) thanks @mistryrn !!
