### ISSUE TITLE
Bug: Add a model page disappears when hover over tabs

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#616]
When I go to add a model and hover over the disabled tabs (images/variants) the page goes blank.
<img width="985" alt="Screen Shot 2020-05-21 at 9 26 22 AM" src="https://user-images.githubusercontent.com/18424138/82565618-b67fc980-9b48-11ea-8d30-8e75d4beb537.png">

**Comment by rosibaj** [comment]
tested on qa environment: 
![image](https://user-images.githubusercontent.com/15824252/82597509-12f9dd80-9b77-11ea-8b9e-9d0aee2be941.png)

lgtm thanks @mistryrn !!!
