### ISSUE TITLE
Blank Fields in Sheet upload do not erase fields when left blank

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#623]
## Description
From Eva, during the Multiple Models deploy:
> I was just typing an update. I refreshed the page and tried the bulk upload again. The error seems to have resolved itself. The bulk upload/overwrite preserves the variant data. Thanks for this fix! There is still an issue with removing data with blank fields in the bulk upload sheet, but this is less pressing than the variant data getting overwritten.
Thanks,
Eva

##  Steps to Reproduce 
1. Bulk upload a text model (example data)
```
HCM-TEST-9999-Z99	Moar Model Types	14	1:8	7 Days	Male	American Indian or Alaskan Native			2020-02-15	PDM-1123		https:/http://hcmi.cancercollaboratory.org/	Colon	T2N0M0	No			Alive	Cytotoxic chemotherapy|Surgery		Metastasis	Ampulla of Darth Vater, Sith Lord	Adenocarcinomas					Yes					
```
https://docs.google.com/spreadsheets/d/1-SlmBBjlRHP_JPIPGlHLG988oN_XpS-KcMT17Vmc1hA/edit#gid=1107755039
2. See that it accurately reflect the uploaded data (screenshots show many different field types) 
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/5bdc36fe-a871-41b1-8985-2e4d6c528886)
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/a4e8e8e4-8896-4c0e-9f98-a36099092f5c)
3. Return to the bulk upload excel.  Remove 1 of each field type from the data in the excel;  For example, remove the fields from the bulk upload excel:
- race
- date of availability
- distributor part number
- source sequence url
- licensing require.

4. Upload the sheet with `YES` selected on overwrite.
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/b59a9248-531d-47b3-872e-2681cf21f4b0)
The sheet uploads successfully and says 1 updated model (as expected)
 ![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/0daa0d09-1ed5-4bc4-9768-7e2d091a35ca)

5. Examine the model data that just got `successfully` updated in the edit model form: 
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/939468d3-5f4d-4a16-bdde-71edf69be891)

In fact, nothing was updated about this model. 

## Expected Behavior.
When a field is left blank, and `YES` overwrite existing models is selected, then that field should not have data.

Note from RB:  not sure exactly when this changes, but it did used to do this (re: discussion on nullable radio button with Eva)

**Comment by akachru-github** [comment]
This was deprioritized. Will be swapping #475 into the sprint instead.

**Comment by mistryrn** [comment]
After a discussion with Eva, it was decided that this change should apply to all non-required fields (not just radio buttons).

Setting any non-required field to blank in the Bulk Upload sheet should erase the data associated with it when the "Overwrite" option is set to `true`.

**Comment by mistryrn** [comment]
Successfully deployed to Prod on April 4, 2023 as part of release 1.20.0
