### ISSUE TITLE
Bug: Upload variant: assessment type not coming through

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#641]
Google doc i uploaded:  https://docs.google.com/spreadsheets/d/1EmqWTiOv2Y49s9PlbUuZJS24mtCdK3wXKzu4B9cvJG8/edit#gid=1133985295

You can see i have filled in assessmen_type in the Google Doc:

![image](https://user-images.githubusercontent.com/15824252/84679648-8a652780-aeff-11ea-94c9-66c730856f7c.png)

The CMS successfully imports the sheet and give a confirmation, but there is no assessment type in the table. 

![image](https://user-images.githubusercontent.com/15824252/84679545-699cd200-aeff-11ea-9fda-39180759dcbb.png)

Additionally, you can see that `expression level` was read in for the clinical variants; This should not happen.  Only histopathological biomarkers should accept an expression level. 
The assessment type doesn't come through on the interface. It should for histopatological variants. 
<img width="1227" alt="2020-06-15_1152" src="https://user-images.githubusercontent.com/18424138/84679079-d2377f00-aefe-11ea-95d9-ace3c76edabe.png">

## Expected behaviour to fix
- [ ] Assessment type should be imported for type histopathological biomarkers variants
- [ ] Expression level should `not` be imported for type clinical variants

**Comment by kcullion** [comment]
@joneubank @rosibaj  this is still a bug, reassigned it

**Comment by rosibaj** [comment]
@joneubank deployed to the site?
