### ISSUE TITLE
Issue with context provider getting stuck on route change to model route 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#65]
Christine tracked the issue down to this commit  https://github.com/nci-hcmi-catalog/portal/commit/e8d9239dda33784eccb85d05207159ee9f45d4b8

- before the commit, the issue does not occur
- pick a filter
- then click on a model to go to entity page.  It does not work - click does nothing
- page freezes and is unusable 

<img width="1680" alt="screen shot 2018-05-14 at 2 02 12 pm" src="https://user-images.githubusercontent.com/15824252/40018948-c9c14c7e-578b-11e8-84ff-b802b708048f.png">

**Comment by alex-wilmer** [comment]
what's the issue?

**Comment by alex-wilmer** [comment]
https://github.com/nci-hcmi-catalog/portal/pull/66

**Comment by rosibaj** [comment]
Example of a query it happened on: 
https://portal.hcmi.cancercollaboratory.org/?sqon=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22gender%22%2C%22value%22%3A%5B%22Male%22%2C%22Unspecified%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22model_type%22%2C%22value%22%3A%5B%222-D%3A%20Suspension%22%2C%223-D%3A%20Other%20e%20g%2B%20neurosphere%2C%20air-liquid%20interface%2C%20etcD%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22molecular_characterization%22%2C%22value%22%3A%5B%22WGS%20of%20normal%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22primary_site%22%2C%22value%22%3A%5B%22Uter%22%5D%7D%7D%5D%7D
