### ISSUE TITLE
FE - Catalog - Add gene and variant search facets

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#650]
- [ ] Gene search facet: https://zpl.io/blqrmRD
<img width="252" alt="2020-06-15_1635" src="https://user-images.githubusercontent.com/18424138/84703476-4a656b00-af26-11ea-8aa0-ff452664e13b.png">

- [ ] Genomic Variant search facet: https://zpl.io/2p60dYN
<img width="260" alt="2020-06-15_1634" src="https://user-images.githubusercontent.com/18424138/84703507-58b38700-af26-11ea-9c3f-f8a799dd43d4.png">

**Comment by kcullion** [comment]
@joneubank Just wondering - if I type in BR in genomic variant search box...then click on the item that matches my search - the search term in the text field changes to "ENST00000658765"
Is there a reason it doesn't display the term that is closest to what I typed instead - which is BRAF G12V?
