### ISSUE TITLE
FE - Catalog - Model Details Page to connect to genomic variant API

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#653]
- [x] connect the new search-genomic variants api
- [x] update model page table component to include pagination ( currently does not)
- [x] Reorder tabs so they are Research Somatic Variants, Clinical Variants, Histopathalogical Biomarkers
- [x]  link to ENTREZ page link (for genes)
https://www.ncbi.nlm.nih.gov/gene/673 --> https://www.ncbi.nlm.nih.gov/gene/[id goes here]
- [x] Decided label: Research Variants tab should be "**Research Somatic Variants**", (Clinical Variants is correct)

Note tab behaviour is on: https://github.com/nci-hcmi-catalog/portal/issues/683

Zeplin link: https://zpl.io/a3n0vW1

**Comment by akachru-github** [comment]
- Cancer gene census is part of the model
- show 500 genes in the Cancer Gene Census, if users want to see more, allow them to download TSV.

**Comment by akachru-github** [comment]
Show all variants with pagination. No census filter required.

**Comment by rosibaj** [comment]
- successfully exported TSV file from the genomic variants with the expected # of rows 
![image](https://user-images.githubusercontent.com/15824252/92281246-284a0c00-eec9-11ea-982a-b80d4894110c.png)

@mistryrn @joneubank LGTM! closing this as no feedback!
