### ISSUE TITLE
FE - CMS Connect CMS table to CMS API 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#660]
Table mockup: https://zpl.io/VxznYrm
- [x] Do a data hookup to the newly created API endpoint to retrun variants from MongAdd pagination to table  component as well as part of this ticket 
- [x] Add table tabs to distinguish Clinical vs Research Somatic Variants 
- [x] Add new upload button for Research Somatic Variants and change button labels (note..the mockup for the Research Somatic Variants has a dropdown arrow. Do no include this dropdown as we will only have one import option for now)
- [x] hover state for Research Somatic Variants button can be found here (ignore dropdown for second button): https://zpl.io/agYgvYR
- [x] Change the instructions to: Select the type of variant you want to add and import a variant list.

Notes for new labels; Research Somatic Variants
<img width="1235" alt="2020-08-14_11-27-36" src="https://user-images.githubusercontent.com/18424138/90265880-3607f680-de21-11ea-9058-634c19fcdbab.png">

Empty state: https://zpl.io/aR5KBez

**Comment by mistryrn** [comment]
@rosibaj a few notes for testing if you get to this ticket before I'm able to wrap up my next round of updates:

- label change to “Research Somatic Variants” hasn’t been deployed yet
- the “+ Research Variants” button just opens the clinical variant upload modal right now, it isn’t hooked up to the import function yet
- the `| <maf-file-name> imported on <timestamp>` text hasn’t been added yet, waiting on an API change to return that data
- the “Research Somatic Variants” table in the CMS currently has front-end filtering (which works now!), but I’ll remove it when we get to the “Clear List” button ticket

I'll let you know when any of this stuff gets updated!

**Comment by rosibaj** [comment]
leaving open until the comments above are merged! moving back to in prgress to retest once they are deployed!

**Comment by rosibaj** [comment]
this all looks as expected and is functioning correctly!  Thanks so much @mistryrn !!!
