### ISSUE TITLE
FE - Import Genomic Variants from gdc

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#663]
--- data hookup to  API to Import MAF File: 
When user clicks "Import MAF from GDC"

- [x] either it works, and the Research Somatic Variants are loaded in the table. Importing message will show if it takes a while, followed by success message when it works (https://github.com/nci-hcmi-catalog/portal/issues/658) 

Or possible errors can occur: 
- [x] More than one MAF file was found in GDC (listing links to the MAFS)  https://zpl.io/a7Anr7K
- [x] Model found but no MAF files found: https://zpl.io/2ZEvZdl
- [x] Model was not found in GDC https://zpl.io/bzgG4DM

**Comment by kcullion** [comment]
@rosibaj added new mockups - please review and remove older if that's ok

**Comment by akachru-github** [comment]
Jon working on fixing showing import errors.

**Comment by rosibaj** [comment]
I've tested lots of different models now - im seeing the errors correctly display in the ui. 

Thanks @joneubank and @mistryrn !
