### ISSUE TITLE
UI restyle: model page feedback

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#664]
- [x] when there are no multiple models - shrink the box. Make it the same height as when there is only one multiple model (remove top and bottom padding of 25px, and make both have the height of 92px)
<img width="567" alt="Screen Shot 2020-06-15 at 10 46 21 AM" src="https://user-images.githubusercontent.com/18424138/84671827-d14e1f80-aef5-11ea-9302-25cb9cebbda3.png">
<img width="561" alt="Screen Shot 2020-06-15 at 10 46 39 AM" src="https://user-images.githubusercontent.com/18424138/84671828-d1e6b600-aef5-11ea-9ed4-f07f8bc484e9.png">

- [x] default to the variant tab to the histopathological variants if there are no clinical variants

- [x] filter on variants - add the x to clear the filter like this search box:
<img width="299" alt="2020-06-15_1311" src="https://user-images.githubusercontent.com/18424138/84686366-cc936680-af09-11ea-96cd-6869c42bc4b5.png">

- [x] Fix alignment on model detail card (same goes for patient card and repo stat card - fix the width of the field labels so the values always show up in same spot)
![image](https://user-images.githubusercontent.com/15824252/84682839-3e68b180-af04-11ea-81b9-e849f3bb0ae8.png)

- [x] can you make the "x" and "check" icons the same size (height) so this box has a consistent height from model to model?
<img width="551" alt="Screen Shot 2020-06-15 at 1 01 20 PM" src="https://user-images.githubusercontent.com/18424138/84685784-d6689a00-af08-11ea-8bd1-31c76b12d8ec.png">

- [x] variant filter bug: first, filter so that you have fewer rows showing, then continue typing letters til the filter causes 0 rows to show, then hit backspace until the reduced row table comes back, then clear the filter… when you clear the filter it will remain at the reduced rows that were showing when the table first came back from 0

- [x] Reorder molecular characterization columns to "Model | Tumour | Normal"

- [x] quick fix for catalog page: use a min-height for the query bar container so that the blank state and the filters on one line have the same height, and there isn't a jump.
<img width="1117" alt="Screen Shot 2020-06-15 at 2 46 34 PM" src="https://user-images.githubusercontent.com/18424138/84694353-0fa80680-af17-11ea-8fa4-d1f8c01987d0.png">

- [x] Cannot scroll images:
http://hcmi.cancercollaboratory.org/model/HCM-KIMC-0051-C64?sqon=%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22setId%22%2C%22value%22%3A%223f24ac08-e6ed-4bb2-abbc-a7556294303f%22%7D%7D
![image](https://user-images.githubusercontent.com/15824252/84710132-9ec21800-af31-11ea-8711-bb22e5d8e3c7.png)

**Comment by rosibaj** [comment]
- [ ] small responsive issue
![image](https://user-images.githubusercontent.com/15824252/85416463-7b542a00-b53c-11ea-9fc2-33eb560f31fb.png)

**Comment by rosibaj** [comment]
@mistryrn followup will be posted in additional tickets - these all lgtm thank you!

**Comment by kcullion** [comment]
@rosibaj @mistryrn maybe I worded this wrong: "default to the variant tab to the histopathological variants if there are no clinical variants"

Can we default to the first tab that has variants? If no variants, then hide tabs

**Comment by rosibaj** [comment]
@kcullion @mistryrn please hold - im setting up this ticket: 
https://github.com/nci-hcmi-catalog/portal/issues/683 

we have a  change request in the order of columns

**Comment by kcullion** [comment]
ok thanks @rosibaj ...just a bit more to it to "default to the first tab that has variants" too
