### ISSUE TITLE
FE - Catalog - Add Most Frequently Mutated Genes chart

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#670]
Front-end code is checked in here: https://github.com/nci-hcmi-catalog/portal/pull/741
Need to pull the correct data into the chart

Zeplin: https://zpl.io/V1KM8Rk
Find colours here: https://zpl.io/2p6enkN
<img width="394" alt="Screen Shot 2020-07-22 at 5 54 23 PM" src="https://user-images.githubusercontent.com/18424138/88232769-6efae400-cc44-11ea-910a-c5ff5dfabfe9.png">

**Comment by rosibaj** [comment]
@kcullion we have some more real data now.  I know you talked to @mistryrn about rounding up to the nearest "pretty number" but i think it looks a little odd on the site.  maybe we can go back to highest as default?  lets discuss tomorrow!

**Comment by rosibaj** [comment]
other than that functionality is testing correctly!
