### ISSUE TITLE
Updates to variant tab bahvaiour

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#683]
- If no variants in any category, show no tabs but do show the `no variant data` message. 
- If data in a variant categories, then show the tabs in this order:
-- Research Somatic Variants
-- Clinical Variants
-- Histopathological Biomarkers
- Default tab selection to the FIRST tab that has variants. For example, if there are no Research Somatic Variants, but there are clinical variants, the clinical variant tab should open by default

**Comment by akachru-github** [comment]
- Covered by other tickets. 
- Leaving open as a checklist

**Comment by rosibaj** [comment]
verified during testing!
