### ISSUE TITLE
Query Bar Update

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#69]
Right now the filters are below the charts, and are not styles correctly
- [x] Move filters to the top
- [x] Remove the word Filters.  The base text should be "Use the filter panel on the left to customize your model search"
- [x] The filter, charts, and table should all be clearly separated and outlined
- [x] Query tag color, parenthesis color, and Clear button should match the spec

**Comment by alex-wilmer** [comment]
Please test changes and lets move  `Add the "Share" Button on the right` to a separate ticket

**Comment by rosibaj** [comment]
Created #80 for the share button.  Tested UI updates listed above - Looks amazing!  Thanks @alex-wilmer
