### ISSUE TITLE
Implement Toggle + the total number of unexpanded models

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#695]
By default, the toggle is off and the table only show expanded models:
Zeplin: https://zpl.io/V1KM8Rk

When the user clicks the toggle, they turn the unexpanded models on in the table:
Zeplin: https://zpl.io/29QRoYW

**Comment by rosibaj** [comment]
@mistryrn persistence looks great, as does the rest of the feature! thank you so much!!
