### ISSUE TITLE
Facet Panel Styling

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#70]
- [x] Facet dropdown should be arrow icon 
![Screen Shot 2018-05-16 at 12.15.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ed0c2a54415b49bc21254d58eeb9cb74fce36f34985619e880690b75c66e15a9bcd61abb50ba208f1a80e0b9df4ec8fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e7495da3103060e177306e0a.png)
- [x] Facet panel doesn't need the vertical colour bar (brown) - that was a Kids First brand element.

- [x] Change the slider bar color to #fc7678
![Screen Shot 2018-05-14 at 1.47.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f76b7191a379f1162c4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19141c95df44de24f55a41b346be7772431.png)
- [x] Show more icon and color should match specs
![Screen Shot 2018-05-16 at 12.10.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ed0c2a51415a4cbc21254d58eeb9cb74fce36f34985619e880690b75c66e15a9bcd61abb50ba208f1a80e0b9df4ec8fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e7495da3133062e17f366e0a.png)
- [x] less (same treatment)
- [x] Only show 4 facet values by default
- [x] Update search Icon to match HCMI Branding
![Screen Shot 2018-05-16 at 12.10.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ed0c2a51415d4cbc21254d58eeb9cb74fce36f34985619e880690b75c66e15a9bcd61abb50ba208f1a80e0b9df4ec8fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e7495da3133266e47e346e0a.png)
- [x] Add the correct amount of space between the edge of the screen and the search  box that appear when you click the search icon, or the more. You can see in this screenshot that they are misalligned
![Screen Shot 2018-05-21 at 7.13.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f26b7191a37ff113284f5a595ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de84951a01b316be1722431.png)

- [x] Add a bit more space between the edge of the screen and the facet [ ] on the left

-[ ] Adjust the boolean count tag to the correct color
![Screen Shot 2018-05-28 at 1.23.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456fb6b7191a379f110284f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19f41c95df44ce44f5da7133e64e4772431.png)

**Comment by alex-wilmer** [comment]
> Add a bit more space between the edge of the screen and the facet [ ] on the left
we had this.. you asked for it to be removed

**Comment by rosibaj** [comment]
@alex-wilmer I agree these are really the same point:  Most correctly stated: 
>  Remove the brown bar, but make sure the facets [ ] stays in the same position i.e retain the same facet spacing that was there with the bar 

if this doesn't make sense, i can show you what i mean on Tuesday in person!

**Comment by lepsalex** [comment]
Ready for review: https://deploy-preview-91--hcmi.netlify.com/
