### ISSUE TITLE
Deploying Gene Model Reference

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#701]
- figuring out what steps to put into the deployment instructions to support Cuong importing it 
- we can host (dropbox)
- give cuong location to import
- instructions to run the mongo import.

**Comment by joneubank** [comment]
https://www.dropbox.com/s/ihjwum2idnzwo0r/dcc-import-genes.json?dl=0

This is the gene reference file, need to write the command to import this so that Cuong can trigger the import.

**Comment by joneubank** [comment]
`mongoimport mongodb://localhost:27017/hcmi --file <filename> --collection genesReference --jsonArray`

**Comment by joneubank** [comment]
Closing this. All the info I need is above, needs to be added to deploy instructions.

They can check if the server has the correct command with `which mongoimport`. If the server doesn't have this available they should run `sudo apt install mongo-tools`.

Note the import command (previous comment) needs the mongodb: address updated to the form mongodb://username:password@host:port/dbname - these parameters are all available in cms/pm2.config.json

**Comment by joneubank** [comment]
This is the command that worked on collab. might be better syntax for Cuong:

`mongoimport --collection=genesReference --jsonArray --uri=mongodb://localhost:27017/hcmi dcc-import-genes.json`
