### ISSUE TITLE
UI restyle: feedback

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#703]
- [x] When clicking on a piece of one of the charts, there's a slight jump in the interface (specifically the query and chart boxes I think)- I think it's the loader as this jump happens on refresh too
- [x]  When i navigate between CMS pages, the page scrolls down on the model list for some wird reason. 
https://drive.google.com/file/d/19_v_IPf9G4A_AFxbKoUoD3hGXHaL5bYx/view
- [x] This scroll down also happens in the data dictionary section and the Create a model form

- [x] Fix footer location on user management page - http://hcmi.cancercollaboratory.org/admin/manage-users

![image](https://user-images.githubusercontent.com/15824252/87457547-8dbf0200-c5d6-11ea-8836-5a8da25630b3.png)

- [x] This link doesn't need to be on a new line, can show in line with the success message (unless there was a reason for this?).
<img width="1066" alt="2020-07-14_1423" src="https://user-images.githubusercontent.com/18424138/87462380-d5955780-c5dd-11ea-8dab-d75043f3410d.png">

**Comment by mistryrn** [comment]
@kcullion / @rosibaj for the last item, I think the links default to a new line in case the notification message contains a bulleted list or if there is no message and just a link.

Should I still make the change to inline it with the rest of the "message details" part of the notification?

**Comment by kcullion** [comment]
@mistryrn  thanks for looking in to that. I think you can leave it as is since there could be a bulleted list. Thanks!

**Comment by rosibaj** [comment]
@kcullion are you still seeing the bump on charts?  i am.

**Comment by kcullion** [comment]
@rosibaj not when I click on these two pieces, but the rest yes. It's like all of the boxes (query, chart and table) get a bit wider. Maybe it's the browser scrollbar though?
<img width="1376" alt="2020-07-17_1031" src="https://user-images.githubusercontent.com/18424138/87797603-f1d10880-c818-11ea-826c-b9cc0f7d2307.png">

**Comment by rosibaj** [comment]
@kcullion hmm ok i see the same thing!  i have a scrollbar regardess, so it _should_ be the same width right?  I dont see any reason for these slices to behave any different than others?

@mistryrn any ideas?

**Comment by mistryrn** [comment]
Fix for the above issue: https://github.com/nci-hcmi-catalog/portal/pull/715

**Comment by rosibaj** [comment]
changes lgtm! thanks so much @mistryrn  you are a 🧙 !!!
