### ISSUE TITLE
Chart Tooltips stick

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#71]
- [ ] click on  a pie slice in the chart
- [ ] click the chart again to remove the filter
- [ ] The tooltip will remain in place.  if you do this a few times, you get a lot of frozen tooltips
![Screen Shot 2018-05-16 at 12.17.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a379ed0c2a56415f49bc21254d58eeb9cb74fce36f34985619e880690b75c66e15a9bcd61abb50ba208f1a80e0b9df4ec8fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e7495da3173f6bee77346e0a.png)

**Comment by rosibaj** [comment]
@alex-wilmer Im happy with the rest of the chart!  I'm ok with your second suggestion to disable the tooltip.
In fact, rather than having the tooltip appear, when the mouse is over a pie slice, can the text in the middle update to that pie slices data?

**Comment by cy** [comment]
i've also just tried everything adskljfliwejcnas :angry: Changing to nivo, works right away.

**Comment by rosibaj** [comment]
😂 this is why you should never try new things :p
