### ISSUE TITLE
FE: CMS: Update title for bulk variant upload + success message

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#733]
Since we now have two types of variants to import, lets clarify that this is the bulk upload for the Clinical Variants only: change the title to 
"Bulk Clinical Variant Upload"

![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/8fa7c0bb-6264-4c13-9642-7bd83ccaae39)

- [x] Also specify "clinical" in the success message: https://zpl.io/agYgvYR
![image](https://user-images.githubusercontent.com/18424138/90268529-268aac80-de25-11ea-96be-bde4be988d07.png)

**Comment by rosibaj** [comment]
lgtm thanks @mistryrn !!!!
