### ISSUE TITLE
FE- CMS- Connect Overwrite existing variants modal

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#734]
If the admin has a list of Research Somatic Variants for a model, and they go to import a new list, they should get a confirmation modal first: https://zpl.io/adeR7wp
<img width="407" alt="Screen Shot 2020-08-14 at 12 12 07 PM" src="https://user-images.githubusercontent.com/18424138/90269921-66529380-de27-11ea-8edc-18ddfff36d2c.png">

**Comment by rosibaj** [comment]
this looks great on the site! thanks @mistryrn !!
