### ISSUE TITLE
Update footer organization

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#743]
Zepplin: https://zpl.io/V1KM8Rk

Urls:
Human Cancer Models Initiative to: https://ocg.cancer.gov/programs/HCMI
ocg.cancer.gov to https://ocg.cancer.gov/

**Comment by rosibaj** [comment]
tested on qa env and urls confirmed by @akachru-github via email.  Lgtm.  thank you @mistryrn !
