### ISSUE TITLE
Genes/Variant Search on Catalog not working

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#761]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/1997cc74-7845-4854-9963-1bacacb336a8)

**Comment by akachru-github** [comment]
Publishing issue.

**Comment by rosibaj** [comment]
Tested
I am seeing a couple variants with an EMPTY id: 
![image](https://user-images.githubusercontent.com/15824252/93507542-d99a6a00-f8eb-11ea-9d24-a6185f80bc37.png)

**Comment by rosibaj** [comment]
artifact f bad data fter troubleshooting wiht @joneubank - reimporting and testing with that

**Comment by rosibaj** [comment]
After reimport discovered:
- bulk actions and deleting a model need to also update the gene/variant search indexes
- these actions were not republishing search indices, leading to ghosted data

fix is in progress

**Comment by rosibaj** [comment]
tested again: 
1. Step 1: http://hcmi.cancercollaboratory.org/model/HCM-BROD-0036-C41
![image](https://user-images.githubusercontent.com/15824252/93511213-72cb7f80-f8f0-11ea-8e7e-a31725cb3e33.png) 
1. Step 2 
![image](https://user-images.githubusercontent.com/15824252/93511284-8c6cc700-f8f0-11ea-9b7c-e9c727c4d295.png)
1. Step 3
![image](https://user-images.githubusercontent.com/15824252/93511249-81199b80-f8f0-11ea-8bd0-6c80609a0771.png)
