### ISSUE TITLE
Model Detail page: TSV file names

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#762]
When the user downloads the TSV form the model page variant tabs, please make the names as follows:

- [x] modelname-research-somatic-variants.tsv

- [x] modelname-clinical-variants.tsv

- [x] modelname-histopathological-biomarkers.tsv

<img width="805" alt="2020-09-08_10-24-04" src="https://user-images.githubusercontent.com/18424138/92489886-48761580-f1be-11ea-8391-c0d350c94abd.png">
<img width="796" alt="2020-09-08_10-24-16" src="https://user-images.githubusercontent.com/18424138/92489894-4c099c80-f1be-11ea-9671-152732667f5a.png">

**Comment by rosibaj** [comment]
lgtm me on the site! thank you @mistryrn !!
