### ISSUE TITLE
Phase 2 508 Violations to Fix

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#778]
- [ ]  Searchable Catalog Page (http://hcmi.cancercollaboratory.org/) - 42 violations
![image](https://user-images.githubusercontent.com/15824252/92795095-1e6b5180-f37e-11ea-81e1-f9d52802fbba.png)

- [x] Model Details Page 5 violations 
**As discussed in slack**, we will not show the disabled external resource buttons. If that resource doesn't exist for the model, please hide the button. And for when there are no resources at all, please display the empty message: "No external resources available." 
![image](https://user-images.githubusercontent.com/15824252/92798785-401a0800-f381-11ea-940c-48ed45a54548.png)

- [x] Cart - 1 violation
![image](https://user-images.githubusercontent.com/15824252/92798915-5e800380-f381-11ea-9c2f-999051d42854.png)

- [ ] Model List Page
![image](https://user-images.githubusercontent.com/15824252/92802902-eadff580-f384-11ea-8ad3-c38b6fd13b43.png)
For new darker colours, please see the zeplin: https://zpl.io/bJm5Z0r
Note: these status tag colours should be updated throughout the cms (on model edit page too)
<img width="1243" alt="2020-09-14_10-46-14" src="https://user-images.githubusercontent.com/18424138/93100874-a485e180-f677-11ea-9551-3cb7935ba2e5.png">

- [ ] Update Model Page
![image](https://user-images.githubusercontent.com/15824252/92803036-0a771e00-f385-11ea-955c-9eff7f3275ff.png)
![image](https://user-images.githubusercontent.com/15824252/92803310-4d38f600-f385-11ea-959d-71a23dbd0acd.png)

- [ ] Add Users Page
![image](https://user-images.githubusercontent.com/15824252/92803387-62158980-f385-11ea-958f-9337408ea997.png)

- [x] Data Dictionary Page
![image](https://user-images.githubusercontent.com/15824252/92940573-48278580-f41d-11ea-9b22-deb6c6015708.png)

**Comment by mistryrn** [comment]
For my own record keeping and progress tracking, here's a detailed list of the violations on the Catalog pages (Search and Model Details). Items in bold are coming from Arranger so fixes may be tricky.

### Catalog Violations
## Search Page
- [ ] Cart collapse button aria-label

> Fix at least one (1) of these issues:
> * Element does not have inner text that is visible to screen readers
> * aria-label attribute does not exist or is empty
> * aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
> * Element's default semantics were not overridden with role="presentation"
> * Element's default semantics were not overridden with role="none"
> * Element has no title attribute or the title attribute is empty
> 

- [ ] **Age At Diagnosis slider aggregation:** 
`<div aria-valuemax="89" aria-valuemin="2" aria-valuenow="2" class="input-range__slider" draggable="false" role="slider" tabindex="0"></div>`

> Fix at least one (1) of these issues:
> * aria-label attribute does not exist or is empty
> * aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
> * Element has no title attribute or the title attribute is empty
> 

- [ ] Toggle button needs label or labelled-by
- [ ] Need to add “Skip to Main Content” link
- [ ] Colour contrast for “EXPANDED/UNEXPANDED” text on gray rows
- [ ] **Unique IDs for items in aggregation cards**
`<div id="Brain" class="bucket-item " content="[object Object]">`
- [ ] **Form elements must have labels**
- Checkboxes in search table
- Dropdown for search table
- [ ] Chart SVGs need alt text

> Fix at least one (1) of these issues:
> * element has no child that is a title
> * aria-label attribute does not exist or is empty
> * aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
> * Element has no title attribute or the title attribute is empty
> 

## Model Details Page
- [ ] External resources: only show available; if none, show empty state
- [ ] Image slider buttons need aria-labels

**Comment by rosibaj** [comment]
Followup implementtion in https://github.com/nci-hcmi-catalog/portal/issues/800
