### ISSUE TITLE
"Resize" cursor appears when attempting to configure columns

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#806]
Eva reported this as a part of testing the GVI tag. 
Looks like the resize cursor is for the columns BEHIND the overlay for the column selector. This is an existing production issue.

**Comment by akachru-github** [comment]
[Uploading... Screen Shot 2020-09-23 at 4.07.34 PM.png ]

**Comment by akachru-github** [comment]
![Screen Shot 2020-09-23 at 4.07.34 PM.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/1d703c33-97b2-42dc-83c1-4b1b62dd6263)

**Comment by rosibaj** [comment]
Confirmed in testing on Oct 02, 2020 
the resize cursor is no longer visible on top of  the column selector
