### ISSUE TITLE
Update "Hub" logo in the footer

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#810]
![image.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/c5ad659a-d44a-4302-951d-9d369ee6b9d1)

Update Hub logo with the following: 
PNG.![logo-hub-organoids-color.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/85a303f0-1d33-4ccf-867d-0dd0e484ece0)

**Comment by rosibaj** [comment]
updates logo looks amazing!
