### ISSUE TITLE
Error on Most Frequent Genes chart 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#830]
- Eva updated the Searchable Catalog to include some new research somatic variant data released at GDC.
- On the main page after publishing the updates, she noticed that the “Most Frequently Mutated Genes” graph is blank 

## Steps to Reproduce
1. Go to https://hcmi-searchable-catalog.nci.nih.gov/ 
2. See that the graph is blank, with a console error:
 ![image](https://user-images.githubusercontent.com/15824252/106774758-7433e500-6610-11eb-908b-ac44c1271514.png)
3. Filtering does exlcude the "bad gene metadata"
- Filter doing a gene search (e.g. TP53,) , then the graph updates to show the mutation data. 
![image](https://user-images.githubusercontent.com/15824252/106775295-fb815880-6610-11eb-9295-cd171b220ab2.png)
- filter on the latest models updated by Eva, and see the graph populate:
-[ link here](https://hcmi-searchable-catalog.nci.nih.gov/?sqon={%22op%22:%22and%22,%22content%22:[{%22op%22:%22in%22,%22content%22:{%22field%22:%22expanded%22,%22value%22:[%22true%22]}},{%22op%22:%22in%22,%22content%22:{%22field%22:%22name%22,%22value%22:[%22HCM-BROD-0007-C49%22,%22HCM-BROD-0095-C15%22,%22HCM-BROD-0098-C15%22,%22HCM-BROD-0103-C71%22,%22HCM-BROD-0104-C71%22,%22HCM-BROD-0194-C15%22,%22HCM-BROD-0195-C71%22,%22HCM-BROD-0196-C71%22,%22HCM-BROD-0198-C71%22,%22HCM-BROD-0199-C71%22,%22HCM-BROD-0213-C71%22,%22HCM-BROD-0223-C43%22,%22HCM-BROD-0227-C43%22,%22HCM-BROD-0229-C25%22,%22HCM-BROD-0332-C43%22,%22HCM-BROD-0339-C43%22,%22HCM-CSHL-0089-C25%22,%22HCM-CSHL-0164-C20%22,%22HCM-CSHL-0244-C20%22,%22HCM-CSHL-0246-C19%22,%22HCM-CSHL-0381-C20%22,%22HCM-CSHL-0433-C24%22,%22HCM-CSHL-0434-C24-A%22,%22HCM-CSHL-0434-C24-B%22]}}]})

Error Seen: 
- "code": "INTERNAL_SERVER_ERROR" - 
- "type": "too_many_buckets_exception",
- "reason": "Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.",

```{
	"errors": [{
		"message": "search_phase_execution_exception",
		"locations": [{
			"line": 7,
			"column": 11
		}],
		"path": ["models", "aggregations"],
		"extensions": {
			"code": "INTERNAL_SERVER_ERROR",
			"exception": {
				"name": "ResponseError",
				"meta": {
					"body": {
						"error": {
							"root_cause": [{
								"type": "too_many_buckets_exception",
								"reason": "Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.",
								"max_buckets": 10000
							}],
							"type": "search_phase_execution_exception",
							"reason": "all shards failed",
							"phase": "query",
							"grouped": true,
							"failed_shards": [{
								"shard": 0,
								"index": "hcmi",
								"node": "Ij-oyhdQQ_WA2HAxq2jhCQ",
								"reason": {
									"type": "too_many_buckets_exception",
									"reason": "Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.",
									"max_buckets": 10000
								}
							}]
						},
						"status": 503
					},
					"statusCode": 503,
					"headers": {
						"content-type": "application/json; charset=UTF-8",
						"content-length": "711"
					},
					"warnings": null,
					"meta": {
						"context": null,
						"request": {
							"params": {
								"method": "POST",
								"path": "/hcmi/_search",
								"body": "{\"query\":{\"bool\":{\"must\":[{\"terms\":{\"expanded\":[\"true\"],\"boost\":0}}]}},\"aggs\":{\"gene_metadata.genes\":{\"terms\":{\"field\":\"gene_metadata.genes\",\"size\":300000}},\"gene_metadata.genes:missing\":{\"missing\":{\"field\":\"gene_metadata.genes\"}}}}",
								"querystring": "size=0&_source=false",
								"headers": {
									"user-agent": "elasticsearch-js/7.9.0 (linux 3.10.0-1160.11.1.el7.x86_64-x64; Node.js v10.16.2)",
									"content-type": "application/json",
									"content-length": "232"
								},
								"timeout": 30000
							},
							"options": {
								"warnings": null
							},
							"id": 38128
						},
						"name": "elasticsearch-js",
						"connection": {
							"url": "http://ncias-p2375-v.nci.nih.gov:9200/",
							"id": "http://ncias-p2375-v.nci.nih.gov:9200/",
							"headers": {},
							"deadCount": 1,
							"resurrectTimeout": 1612370622361,
							"_openRequests": 0,
							"status": "dead",
							"roles": {
								"master": true,
								"data": true,
								"ingest": true,
								"ml": false
							}
						},
						"attempts": 3,
						"aborted": false
					}
				},
				"stacktrace": ["ResponseError: search_phase_execution_exception", "    at IncomingMessage.response.on (/local/content/hcmi/install/node_modules/@arranger/server/node_modules/@elastic/elasticsearch/lib/Transport.js:240:25)", "    at IncomingMessage.emit (events.js:203:15)", "    at endReadableNT (_stream_readable.js:1145:12)", "    at process._tickCallback (internal/process/next_tick.js:63:19)"]
			}
		}
	}],
	"data": {
		"models": {
			"extended": [],
			"hits": {
				"total": 148
			},
			"aggregations": null
		}
	}
}
```
4. Clearing the search does not update  the graph data. 
5. Clicking the “Human Cancer Models Initiative” text in the upper left hand corner, then the graph still remains the same and does not reset the previous TP53 filter.
6. Refresh from the Chrome “refresh” button DOES reload the graph, the graph goes back to blank.

## Expected Behaviour
Chart is not blank/does not error out.

**Comment by mistryrn** [comment]
Quick update before EOD:
- looks to be elasticsearch-related, due to the **`search.max_buckets`** setting
- when looking at the entire data set (no filters applied), the aggregation to calculate the most frequently mutated genes fails because it attempts to create more buckets than the max number of buckets we have configured (this is why it works when you apply a filter)
- the max is currently set to **10,000**, increasing that setting should fix this error but I’m unsure what the optimal number is. As the data grows, the number of buckets required will also grow, so this could happen again

Via https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket.html
>  The maximum number of buckets allowed in a single response is limited by a dynamic cluster setting named **`search.max_buckets`**. It defaults to **65,535**. Requests that try to return more than the limit will fail with an exception

^ Not sure why ours seems to be set to **10,000** if the default according to the docs is **65,535**

I’m also unsure where the actual config change needs to be made. This doc (https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html) lists 3 possible config files:
- `elasticsearch.yml` for configuring Elasticsearch
- `jvm.options` for configuring Elasticsearch JVM settings
- `log4j2.properties` for configuring Elasticsearch logging

So I’m guessing it would be `elasticsearch.yml` somewhere on the prod server? I’m not too familiar with the prod deployment or the ES environment in general.
