### ISSUE TITLE
Hide Expanded/Unexpanded Toggle 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#831]
- [x] Hide the Expanded/Unexpanded Toggle behind a feature flag until the first unexpanded model is ready to be added. 
![image](https://user-images.githubusercontent.com/15824252/107061266-f570b080-67a5-11eb-8908-c6effecabc6a.png)

**Comment by rosibaj** [comment]
QA on Feb 19, 2021:

Toggle is gone from UI: 
![image](https://user-images.githubusercontent.com/15824252/108526564-481a9400-729f-11eb-9a0c-47d68d8e6c72.png)
 
@mistryrn looks great!  before i close this ticket, for reference, can you please include brief instructions on which feature flag would need to be enabled in future to make the toggle reappear?

**Comment by mistryrn** [comment]
### Instructions

To. re-enable the toggle, follow the instructions in `ui/src/components/search/Search.js` and uncomment the necessary lines to make the toggle reappear
