### ISSUE TITLE
UI - Check for GDC variants - Button and Modal

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#846]
- [x] Add a button to the model management screen for "Check for GDC Variants"; Zeplin: https://zpl.io/aRnmJMK
![image](https://user-images.githubusercontent.com/18424138/110034852-ecbdbc80-7d08-11eb-9395-92c7bb98d399.png)

Build the modal that feeds in the two types of modals (Models with variant data already imported to HCMI and Models with no variant data imported) and offers two import options (import new, import all).

**Modal states:**

- [x] 1. This may take time, so please implement a loader: Zeplin: https://zpl.io/2E5dJjn
![image](https://user-images.githubusercontent.com/18424138/110036219-aa957a80-7d0a-11eb-807f-89ab4e77c817.png)

- [x] 2. The audit results table, ability to download this as a tsv and options for inport. Zeplin: https://zpl.io/VO4XwAY
![image](https://user-images.githubusercontent.com/18424138/110035782-14f9eb00-7d0a-11eb-8677-e5b552620a50.png)

- [x] 3. a. If Eva chooses the second option to import all and clicks the import button. Zeplin: https://zpl.io/bJoQJJn
![image](https://user-images.githubusercontent.com/18424138/110036375-e597ae00-7d0a-11eb-8f2e-aaa4bdc43e53.png)

b. Then show a confirmation message and change the button text to "Yes, Import"
![image](https://user-images.githubusercontent.com/18424138/110036493-17a91000-7d0b-11eb-81c7-982eba6a85bd.png)

**Comment by rosibaj** [comment]
LGTM!
