### ISSUE TITLE
UI - Messaging - Bulk Import Errors with No Actions Required

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#852]
There are three types of errors that don't require action from Eva. Some look slightly different for bulk vs. individual upload. 

**FOR BULK UPLOAD**
- [x] We will combine these two types of errors into **one banner**: 1. Model is not found in GDC or 2. Model is found by no MAF files are found. 
So any model that has this error will be added to this banner table and the count for that error. Zeplin: https://zpl.io/bLvLzWD
![image](https://user-images.githubusercontent.com/18424138/110129301-cdb93c00-7d95-11eb-863a-3c6ee7fc6c74.png)

**FOR INDIVIDUAL UPLOAD**
Note; these banners already exist, just the wording has changed to make them consistent with the bulk combined banner. 
- [x] Models not found in GDC: https://zpl.io/bWMBOek
![image](https://user-images.githubusercontent.com/18424138/110132678-6dc49480-7d99-11eb-8d3a-049e0f1f073f.png)

- [x] Models found but no MAFS: https://zpl.io/aME5O1z
![image](https://user-images.githubusercontent.com/18424138/110132309-0870a380-7d99-11eb-8557-b57ad4d6c4d8.png)

**GDC API ERROR (NEW)**
- [x] Lastly, there's the general GDC API failure banner (both bulk and individual upload could result in this):
zeplin: https://zpl.io/Vk4YqKq
![image](https://user-images.githubusercontent.com/18424138/110128979-63080080-7d95-11eb-9532-e4e2675498b4.png)

**Comment by rosibaj** [comment]
## Issue No. 1 - Error Message not appearing

### Steps to Reproduce 
1. delete these 4 models from the catalog: 
```
HCM-BROD-0002-C71
HCM-CSHL-0245-C18-A
HCM-BROD-0332-C43
HCM-CSHL-0434-C24-B
```

2. Bulk import the sheet of models with the following options: https://docs.google.com/spreadsheets/d/1dJGcDCmPecuwH9I-0oBPQMs_HFdqGnQ95BEOED87k-0/edit?urlBuilderDomain=oicr.on.ca#gid=2108205267
![image](https://user-images.githubusercontent.com/15824252/115919059-53787000-a446-11eb-806d-c42a5b20c11f.png)

3. see the process run.  3 failed but i didnt get an error message. 
![image](https://user-images.githubusercontent.com/15824252/115919654-1e205200-a447-11eb-95a5-3e98197f8957.png)

**Comment by rosibaj** [comment]
closing this issue as the error messages are looking good!
