### ISSUE TITLE
BE - Stop Import Endpoint 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#857]
To support: https://github.com/nci-hcmi-catalog/portal/issues/856

Endpoint should :
- [ ] stop a bulk export. 
- [ ] Report a success when ready so that the UI can change the progress banner to the success banner with how many model variants successfully imported.

**Comment by akachru-github** [comment]
- If an import is in progress, don't stop it. Stop the ones that have not started
