### ISSUE TITLE
Unified Export UI/BE: Download Button

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#876]
Develop the button for the front end for the unified export download: 
![image](https://user-images.githubusercontent.com/15824252/113725641-8211ef00-96c1-11eb-9cdd-04ecd28d1f23.png)

- [x] When models are not unselected, the entire query is taken: 
https://zpl.io/bomW8mG

- [x] When models are selected:
https://zpl.io/a34k1PW

- [ ] When items are selected, the yellow button in the model drawer label changes for consistency: `TSV (All Columns) 
`https://zpl.io/VxAG0Gx

**Comment by akachru-github** [comment]
Both UI and BE filters will be applied with this ticket. 
- Selected Models
- Selected Columns

**Comment by rosibaj** [comment]
Tested May 19, morning 

- no issues found with exports 
- no issues found in navigation/dropdown 
Thank you @joneubank !
