### ISSUE TITLE
Hover bubbles / Tooltips: Investigate Arranger changes for facet tooltips

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#884]

**Comment by joneubank** [comment]
I was cleaning up code related to the Table download functionality and it appears that providing custom header in the table creates a UI error when the download button is clicked. The specific cause of this crash I am not sure of, but fixing it will require a change to the Arranger code that handles the download.

**Comment by joneubank** [comment]
More experimenting and I think there is an easy solution to the above comment, specifically that if you wrap the component in an anonymous function then the json object parsing that is done doesn't break anymore, so the correct way to implement a custom header is:
`[{content: { field: 'fieldName', Header: ()=> <>Custom Header Content</>}}]`
