### ISSUE TITLE
Security upgrades

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#885]
![image](https://user-images.githubusercontent.com/15824252/115425047-3e44dc80-a1cd-11eb-91b0-7447c59783ca.png)

**Comment by akachru-github** [comment]
FYI: @mistryrn , I have added this to the 1.10.0 tag release!

**Comment by rosibaj** [comment]
@mistryrn i still see this alert from 2 hours agp: 

![image](https://user-images.githubusercontent.com/15824252/116611591-8b7b2980-a904-11eb-9f89-41b3b478e2cb.png)
