### ISSUE TITLE
Model Details Page: Add hover-over question-mark icons

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#891]
**Zeplin for Hover bubbles for model detail page** https://zpl.io/2ZMrmdd

**Behaviour:** there is one hover bubble that has a link in it. Let's do the following (taking inspiration from Wikipedia when you hover over any link: https://en.wikipedia.org/wiki/Black_and_Yellow)
1. always make it so the user can hover over the ? icon AND the open hover bubble content area to keep it open. When they move their mouse away from the hoverbubble or the ? icon then the bubble disappears. 
2. If there is a link in the content, make that hover bubble clickable (with a hand cursor when user's mouse is on it). If there is no link, then the user can hover over the hoverbubble to keep it open but the mouse would be the usual arrow cursor. 

![image.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/cb94be8f-023e-4d76-90aa-44afbf2bb5cb)

- [x] Question mark icons on each of the following cards, each with it's own block of descriptive text that can be found here: https://docs.google.com/document/d/1aLXBKtOOYJ2y7OJnrOC6veNtycH9CMjUsPsWDv228uw/edit?usp=sharing
  - Model Details
  - Multiple Models From this Patient (The same description will need to appear both here and on the Landing/Search page)
  - Available Molecular Characterizations (The same description will need to appear both here and on the Landing/Search page)
  - Patient Details

![image](https://user-images.githubusercontent.com/18424138/115927923-3dbd7780-a453-11eb-81b1-84bc68d65f15.png)
- [x] Text at the top of the "Variants" section for each of the following tabs, the content for each blurb can be found here: https://docs.google.com/document/d/1aLXBKtOOYJ2y7OJnrOC6veNtycH9CMjUsPsWDv228uw/edit?usp=sharing
  - Research Somatic Variants  (The same description will need to appear both here and on the Landing/Search page)
  - Clinical Variants  (The same description will need to appear both here and on the Landing/Search page)
  - Histopathological Biomarkers  (The same description will need to appear both here and on the Landing/Search page)

**Comment by rosibaj** [comment]
Tested Friday May 14, 2021.  Lgtm thanks @mistryrn !
