### ISSUE TITLE
Check for GDC Variants - import all gave me 2 sets of same banners too

### ISSUE THREAD

**Issue by kcullion** [nci-hcmi-catalog/portal#894]
I get the same error banners twice again on the "Check GDC for Variants' button. My suspicion is because I'm closing the banners and trying it again without refreshing the screen in between?

1. Click check GDC for variants button and choose the first radio button.
2. close the banners that result from that...something like this:
![image](https://user-images.githubusercontent.com/18424138/116138761-37bdd580-a6a3-11eb-87f9-c213c4d522ef.png)
3. Click check GDC for variants button and choose the import all, second radio button.
I don't see the large banner anymore, and some get reported twice.
![image](https://user-images.githubusercontent.com/18424138/116139290-dc401780-a6a3-11eb-90d3-3b9bd558d9a2.png)

4. If I refresh this screen, then I get the correct error banners including that large "no action required" one

![image](https://user-images.githubusercontent.com/18424138/116139481-0c87b600-a6a4-11eb-9fe8-dbc61028dd67.png)

### Expected Behaviour
I don't think the admin should need to refresh in between actions.

**Comment by rosibaj** [comment]
Tested April 29, 2021 afternoon
- multiple banners did not appear when initiating all imports in succession
- for each try, the correct and expected banners appeared
