### ISSUE TITLE
Tooltip / Hover Bubbles:  improvement to text on the Model Details page

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#928]
Tooltip text for variants on individual model pages: can the text be updated slightly to include the following **bolded** text?
- "**Research Somatic** Variants are imported…."
- "**Clinical** Variants are identified through…"
- "**Histopathological** Biomarkers are identified through…"

**Comment by mistryrn** [comment]
Updated in https://github.com/nci-hcmi-catalog/portal/pull/931

Note that this change was applied to _all_ instances of the variant-related tooltips (i.e. on the Search table hover bubbles as well), not just the Model Details page.
