### ISSUE TITLE
Provide static ordering of columns in the "Clinical Variant Data" TSV file

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#930]
For the Clinical variant data tsv files, can the columns in the exported file be arranged in a specific order like we have on the individual model page table? (e.g. Name, Genes, Assessment type, Expression level, Type).

**Comment by rosibaj** [comment]
Test data (Model with both data types): https://hcmi-searchable-catalog.nci.nih.gov/model/HCM-BROD-0005-C41?sqon=%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22setId%22%2C%22value%22%3A%222cd28231-72c3-4063-af52-b8511f2a0096%22%7D%7D 
Examples data:
```
name genes type category assessment_type type assessment_type expression_level
CD99 CD99 Histopathological biomarker Histopathological Biomarker IHC Positive
EWSR1-FLI1 EWSR1, FLI1 Clinical Translocation
```

**Comment by rosibaj** [comment]
tested July 05, 2021 
 Looks great - thank you @mistryrn !
