### ISSUE TITLE
Admin Override for MAF input

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#936]
The following is an explanation of how a model in HCMI has data imported from the GDC: 

1. Starting with the model name in the CMS, for example “HCM-CSHL-0056-C18”, we make a request to the GDC API looking for Cases with the Submitter ID (`cases.submitter_id`) matching that model name.
2. Once we have a matching Case for a given model name, we find all Files for that case which are of the “Open” Access and “MAF” Data Format (`files.acces`s, `files.data_format`).
3. Because of how the GDC GraphQL API works, this gives us two lists: one list of matching Cases (in this example, the list only has one Case, for the one model name we have searched for), and one list of matching Files.
4. The next step is to iterate through the two lists and combine the data such that for a given model name, we can iterate through its Files and determine if there are NGCM MAFs which we can import

Examining the model that was pointed out in the comment, in the HCMI Searchable Catalog HCM-CSHL-0434-C24-A and HCM-CSHL-0434-C24-B are two separate entities with unique identifiers.

To support import of MAFS for this type of case (multiple model with no matching case in GDC)

- Currently, the import logic is using file name and file UUID to perform the actual import of the variant data. 
- The Manual Override for GVI feature will use the same logic to perform the import, except instead of automatically detecting what file to import from the GDC based on the model name, the Manual Override method will use a Name and UUID manually inputted by the Content Manager. Below is an example where these fields can be located for a file in the GDC interface: 

**Zeplin Links**:

- [x] Restyle the variant button into a dropdown. `Automatic Import from GDC` should lead to the current path (i.e auto import, or modal if > 1 NCGM MAF) Zeplin: https://zpl.io/2jqQqeO
- [x] The `Manual Import from GDC` should follow a new path. 
Zeplin: https://zpl.io/VQJBJem
![image](https://user-images.githubusercontent.com/15824252/121053810-bbcaa900-c789-11eb-86f0-8790c37074ae.png)
- [x] Error state if user makes mistake on import ids. Zeplin: https://zpl.io/VOLPLqP

**Comment by rosibaj** [comment]
### Tested June 23, 2021 10:39
- using the test model highlighted above i was able to import the new file: 
  - https://portal.gdc.cancer.gov/files/7e5392a8-e921-4748-a464-553b7525258e
  - ![image](https://user-images.githubusercontent.com/15824252/123116979-5b856980-d40f-11eb-9427-13d5d56436dc.png)
- 99 variants imported, and 99 in the file as well: 
  - ![image](https://user-images.githubusercontent.com/15824252/123117503-cb93ef80-d40f-11eb-88b9-8f03980574c5.png)


## Issues 
- [ ] 1) The automatic case URL is not correct. 
- expected case url: https://portal.gdc.cancer.gov/cases/c4025241-d423-4daa-b0fc-b27873d4e314 
- actual case url  that was made: https://portal.gdc.cancer.gov/cases/30ad857e-34d5-4ae1-8ca1-e962d10d6583
- ![image](https://user-images.githubusercontent.com/15824252/123117982-3ba27580-d410-11eb-88a8-5419165359de.png)
- [ ] 2) The `Sequence URL` field was not populated by the automatic import: 
  - ![image](https://user-images.githubusercontent.com/15824252/123118694-dc913080-d410-11eb-8830-7d939b7802ba.png)
  - Should follow the same format, with the caseid as input: 
  - `https://portal.gdc.cancer.gov/repository?facetTab=files&filters={"op":"and","content":[{"op":"in","content":{"field":"cases.case_id","value":["CASE_ID_GOES_HERE"]}}]}&searchTableTab=files`

**Comment by mistryrn** [comment]
Regarding the above feedback points:
- when performing a manual override, we do not have access to the case ID, so neither of the fields dependent on case ID will be generated (Model URL and Sequence URL)

As for the first point, I believe that incorrect URL was already present from the Google Sheet used to bulk import the data: https://docs.google.com/spreadsheets/d/1qGTjLjWBS1epMK_qB-FWk_VyhR5B7kviPrSKm-sFYBE/edit#gid=1253853088

You can see the incorrect case ID present for this model on that sheet.
