### ISSUE TITLE
Netsparker Updates

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#954]
- review the first 4 alerts in the Netsparker report (ask @rosibaj) for cross-site scripting 
- take a quick look at the yellows; any quick wins we can resolve?

**Comment by mistryrn** [comment]
Took a look at the report:
- for the Cross-Site Scripting (XSS), like Jon said, none of these are important. Looks like it’s  just looking at the graphql response, which is harmless
- didn’t see any of the “Low” ones as “quick wins” that we can easily resolve. Some might be with further investigation, not sure if we want to put the effort in though:
  - The 500 error is something on the NCI/CBIIT side, would require effort/investigation from their team (not reproducible locally or on collab, points to being an environment/server-specific issue)
  - I think the version disclosure ones would require config changes from their team as well (not 100% sure about this though, would have to look into that)
  - For the “Misconfigured Access-Control-Allow-Origin Header” one, I think we actually do need that header
  - For “Missing X-Frame-Options Header”, I believe this would also be a change required on their end

**Comment by akachru-github** [comment]
Cross site scripting turned out to be benign. Closing.
