### ISSUE TITLE
Issues with template/bulk import

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#962]
- intermittently observe
- 400/500 
![image](https://user-images.githubusercontent.com/15824252/135511230-55d71072-0b71-4538-8640-06dc2b1b716c.png)

**Comment by mistryrn** [comment]
Migrated to Google Identity Services in release 1.18.0, deployed on September 16 2022. New library requires more frequent authentication, which should resolve these intermittent bulk upload issues related to Google auth.
