### ISSUE TITLE
Under external resources, change “Model Source” pill text to “Case Metadata”.

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#964]

**Comment by kcullion** [comment]
@mistryrn @akachru-github 
The button on the UI looks good.

Only suggestion I would make is changing the label in the CMS to `Case Metadata URL`, or at least adding "case metadata" to the description of this field. 
Just from a standpoint of someone new coming in to use the CMS and wondering what that field maps to on the UI.
![image](https://user-images.githubusercontent.com/18424138/138343773-7feb1dec-5c0c-4016-ae8f-2fb0986dc4e2.png)

Also should we change the label in the bulk spreadsheet while we're at it to `Case Metadata URL`? 
![image](https://user-images.githubusercontent.com/18424138/138343873-434dc338-8be5-4e99-b8ac-38e42cb69d96.png)
