### ISSUE TITLE
Update "Molecular Characterization" table

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#966]
Remove “Targeted-seq” from the Molecular Characterization Table matrix, and replace with “DNA Methylation Array”, since there are cases with methylation data. No Targeted-seq data is going to be available for these models.

The table is powered by manually inputted data when creating the model under "Molecular Characterizations".  "DNA Methylation Array" is not currently an option as a checkbox here.

We will need to:
- [x] Remove "Targeted Seq" from the Molecular Characterizations table AND model creation page
- [x] Add "DNA Methylation Array" to the model creation page as a new selection
- [x] Add "DNA Methylation Array" to the Molecular Characterizations table
- [x] Upload bulk upload sheet to reflect the adding of a new checkbox and removal of the old one.

**Comment by kcullion** [comment]
Looks great in production...closing now
