### ISSUE TITLE
Performance optimization for model changes

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#984]
Currently, when updating and publishing any fields within a given existing model, the HCMI application evaluates all fields for publishing whether or not they are part of the set being changed. 

Every field (including the variant data) will be sent to Elasticsearch during the publishing process. 

The OICR team is proposing to optimize this process by only sending the fields being changed to Elasticsearch as a part of the publishing process. 

This will significantly reduce the amount of data being sent and retrieved, which will improve the performance of updates to models that already exist. 

Note that while publishing changes to existing models should have improved performance, adding a new model with many variants to the system will still have to send all of the data to Elasticsearch for publishing

**Comment by mistryrn** [comment]
@b-f-chan here's a document outlining the steps necessary to test and evaluate the optimizations: https://docs.google.com/document/d/1jmCOJHt9Jx9hPxb8_WmYflNM5HtdWpC_Co4MSmpPEGs/edit?usp=sharing

**Comment by b-f-chan** [comment]
Tested jointly with @mistryrn on Dev/QA VM.  Noticeable performance enhancements were observed, recorded as follows:

**(1) Test Case 1: Single model, multiple variants (2793), molecular characterization changes:**

- Before: ~41s 51ms
- After: ~4s 3ms

**(2) Test Case 2: Single model, clear the variants, NO molecular characterization changes**

- Before: ~14s 23ms
- After: ~12s 15 ms

**(3) Test Case 3: Single model, add all variants back (2793), NO molecular characterization changes**

- Before: 21s 31ms
- After: 16s 7ms

This ticket is ready for deploy to CBIIT when ready.

**Comment by mistryrn** [comment]
Deployed to Prod on August 2nd as part of Release 1.16.1
