### ISSUE TITLE
Google integration issue in production

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/portal#986]
- Experienced intermittently. 
- When it happens, Incognito mode can be used to get around it.

**Comment by scottcain** [comment]
Presumably related to https://github.com/nci-hcmi-catalog/portal/issues/962

**Comment by mistryrn** [comment]
Migrated to Google Identity Services in release 1.18.0, deployed on September 16 2022. Should resolve these intermittent Google auth issues.
