### ISSUE TITLE
Fix Entity page banner (Safari only)

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#99]
Generally looks great in safari - the only problem is that Entity carousel bar at the top colour is not rendering properly, nor is the icon background colour on the entity page share button. 

![Screen Shot 2018-06-06 at 1.31.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f56b7191a379f1112a4f5b585ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19041c95df443e24d53a71a3666e7752431.png)

**Comment by rosibaj** [comment]
Generally looks great in safari - the only problem is that Entity carousel bar at the top colour is not rendering properly, nor is the icon background colour on the entity page share button. 

![Screen Shot 2018-06-06 at 1.31.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2ee6177753f500131977d7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f56b7191a379f1112a4f5b585ecc3c4a4356bcbbd671f3e57862804e0ebcd5395e74953914a8ec871bee01ba24de4ad3b3e98844d2f42f67b6d5db1063474f4dcbed5727a19041c95df443e24d53a71a3666e7752431.png)

**Comment by kcullion** [comment]
Another fix (not just safari)
- can you make the arrow and facet label be the hit-target for opening and closing the facet. Just having the arrow as the hit target is quite small.

![screen shot 2018-06-07 at 5 09 12 pm](https://user-images.githubusercontent.com/18424138/41126449-85ab4fce-6a75-11e8-9678-caf115f72a38.png)
